### ISSUE TITLE
Шаг 8: определение количества импортируемых записей

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#10]
Может ли метод Restore возвращать численное значение?
Возникает одна проблема при импорте, когда импортируем записи, то могут быть невалидные, а следовательно нужно от конечного числа записей, которые мы импортируем, отнять это количество невалидных записей.  Это можно сделать только в методе Restore, но на диаграмме классов он вроде как ничего не должен возвращать, да и это как-то не логично, что метод, восстанавливающий состояние возвращает  какое-то число.

Общее количество импортируемых записей мы получаем на snapshot. Метод GetStat() тут тоже использовать не вариант, т.к. мы не знаем какое количество записей было обновлено.

**Comment by alexander-rykov** [comment]
@vitalmizevich давайте рассмотрим разные варианты решения. насчем все-таки с Restore.

1) Restore проверяет данные записи на валидность и возвращает количество импортированных записей. если запись не валидна, то он просто пропускает ее. таким образом, N записей в снепшоте != M импортированных записей.
2) Restore проверяет данные всех записей на валидность ДО внесения изменений в список сервиса, в случае появления невалидной записи Restore выбрасывает исключение. список сервиса остается цел. таким образом, происходит импорт всех записей или импорт не происходит вообще. в этом варианте стоит добавить новый тип исключения.

посмотрите на диаграмму последовательности и предложите другие варианты, которые можно реализовать для проверки данных на валидность.

подумайте, какие плюсы и минусы есть у различных решений.

**Comment by vitalmizevich** [comment]
С точки зрения импорта первый вариант более предпочтительный перед вторым. Допустим, если данные у нас импортируются с БД в которой очень большое число записей и какая-то запись ближе к концу невалидна, то получаеся ситуация, когда у нас невозможен импорт вообще, пока мы не исправим или не удалим "плохие данные". 

В первом же случае, если просто пропускать невалидные записи и возвращать только количество импортируемых записей, возникает проблема, когда мы не знаем какие именно записи не валидны. Конечно, можно выводить на консоль инфрмацию о том, что запись содержить ошибку, при этом добавив в метод Restore дополнительный out параметер целочисленного типа, который будет увеличивать с каждым таким случаем (в принципе, я так и реализовал), но @SvetlanaSavich натолкнула на более лучший вариант решения проблемы. Т.к. данные мы восстанавливаем в BLL слое, то консоль использовать здесь не разумно, а следовательно лучше чтобы у нас был какой-то логгер, который накапливал соответсвующие исключения во время импорта, пройдя по которым мы сможем определить количество невалидных записей и соответствующие ошибки.

**Comment by alexander-rykov** [comment]
Номер 1.

@vitalmizevich:

_С точки зрения импорта первый вариант более предпочтительный перед вторым_

Обратите внимание, что Вы назвали один вариант предпочтительным на основании собственного предположения. А ведь требование может быть абсолютно противоположным. Например, требуется добавить все данные только целиком. Для того, чтобы сделать правильный выбор нужно _требование_.

Из книги Вигерса ["Разработка требований"](http://static1.ozone.ru/multimedia/book_file/1010427104.pdf):

_Консультант Брайан Лоренс предположил, что требования — это «нечто такое, что определяет выбор дизайна» (Lawrence, 1997)_

_Наше любимое определение сформулировано Иеном Соммервиллем и Питом Сойером (Ian
Sommerville и Pete Sawyer, 1997): Требования это спецификация того, что должно быть реализовано. В них описано поведение системы, свойства системы или ее атрибуты. Они могут служить ограничениями в процессе разработки системы._

Выбор конкретной реализации импорта ("выбор дизайна", "выбор ограничения системы") зависит от требований. В случае задания конкретного требования на этот счет нет, поэтому можно реализовывать импорт по-разному.

**Comment by alexander-rykov** [comment]
Номер 2.

Предложение @SvetlanaSavich неплохое.

Я предлагал посмотреть на [диаграмму последовательности](https://raw.githubusercontent.com/epam-dotnet-lab/file-cabinet-task/master/images/wrong-filecabinetrecord-import-options.png) и рассмотреть другие варианты:

![wrong-filecabinetrecord-import-options](https://user-images.githubusercontent.com/19323417/67150442-2763b800-f2c0-11e9-8692-f2d7cb10d22e.png)

Красным выделены возможные варианты:

* Можно прерывать чтение CSV файла, если встретились неправильные данные.
* Можно научить snapshot проверять данные на валидность после загрузки данных из CSV.
* Можно брать данные из snapshot после загрузки и проверять их на валидность.

Есть где развернуться фантазии.

**Comment by vitalmizevich** [comment]
Немного поразмысли, пришел к выводу, что количество невалидных записей (если рассматривать вариант, что мы успешно прочитали все данные из файлов и не было ошибки конвертации) можно получить через метод Restore, не меняя сигнатуры. Просто нужно будет собирать все исключения, а в конце, если их больше 0, выбросить Aggregate Exception. Вариант похож на тот, что был описан мной выше (про логирование), но интересно оценить его с точки зрения дизайна.

**Comment by alexander-rykov** [comment]
Нет, этот вариант "ломает шаблон", поэтому его использовать не стоит.

_Когда в приложении происходит ошибка, есть два диаметрально противоположных подхода к обработке этой ошибки:_
_Forgive! подход: приложение продолжает выполняться и старается минимизировать последствия ошибки._
_Fail Fast! подход: приложение немедленно прекращает работу и сообщает об ошибке._
https://habr.com/ru/post/218325/

forgive - это пропускать невалидные записи, валидные добавлять.
ff - это проверить записи перед добавлением, прекратить импорт в случае невалидной записи, не вносить изменения в список сервиса если есть невалидные записи.

ваше предложение микширует оба подхода. исключение обычно выбрасывается, когда операция *прерывается*. в вашем случае - операция завершена успешно (пусть и частично), но есть ошибки при выполнении операции.
