### ISSUE TITLE
Шаг номер: 14

### ISSUE THREAD

**Issue by Tounderz** [epam-dotnet-lab/file-cabinet-task#101]
Здравствуйте, Александр. Можно ли использовать для отрисовки таблицы CTable пакет?

**Comment by Tounderz** [comment]
Здравствуйте. И второй вопрос: После каждой записи долго быть разделение строки или как в скрине, только шапка отделена и в конце таблицы?

**Comment by alexander-rykov** [comment]
1. используйте. а что за пакет такой?
2. шапка и в конце.

**Comment by Tounderz** [comment]
Спасибо)
вот пакет: https://russianblogs.com/article/99461143664/
