### ISSUE TITLE
Шаг 1-3: необходимость написания тестов

### ISSUE THREAD

**Issue by ilyaVdovenko1** [epam-dotnet-lab/file-cabinet-task#102]
Подскажите пожалуйста, ни в одном из шагов ничего не упоминается про тесты, тем не менее проверка корректности каждого шага усложняется без unit и функциональных тестов, поэтому вопрос: можно ли добавить в проект тесты или же проверки корректности делать в ручном режиме?

**Comment by alexander-rykov** [comment]
добавляйте, если считаете нужным
