### ISSUE TITLE
Шаг 5: добавление параметров командной строки

### ISSUE THREAD

**Issue by Sergey-Yushkevich** [epam-dotnet-lab/file-cabinet-task#103]
Подскажите, пожалуйста, как добавлять параметры командной строки и запускать приложение через консоль(на windows используется .exe файл) для пользователей macOS. Так как не могу найти информацию ни о запуске .exe-файла(альтернатива .app на MacOS), ни о добавлении параметров

**Comment by alexander-rykov** [comment]
никогда не пользовался macos, не знаком с ее командной строкой. вот здесь есть какой-то мануал:
https://www.michaelcrump.net/part3-aspnetcore/
