### ISSUE TITLE
Шаг 10: Валидация ввода после рефакторинга

### ISSUE THREAD

**Issue by simufkwikler02** [epam-dotnet-lab/file-cabinet-task#104]
На этот вопрос уже отвечали, но я не очень понял, хотелось бы поподробнее узнать.
Там писали, что не нужно использовать IRecordValidator для валидации данных при вводе.
Вопрос, по каким правилам нужно проводить валидацию ввода?
Просто валидацию же нужно проводить в зависимости от того, custom или default у нас валидатор. А эта информация находится в валидаторе, который мы создали, с интерфейсом IRecordValidator.

**Comment by alexander-rykov** [comment]
на этом шаге вы можете использовать тот же объект валидации, который вы передаёте в сервис. вот только ходить за ним в сервис не нужно. храните ссылку на этот объект в другом месте.

**Comment by simufkwikler02** [comment]
Тогда возникает вопрос, для ввода данных через консоль нужно проверять данные по одному, а наш валидатор умеет проверять только всю запись целиком. Как тогда проверять ввод данных по одному?
Или нужно через ValidatorBuilder создавать новый валидатор, который будет проверять например только имя?

**Comment by alexander-rykov** [comment]
в интерфейсе таких методов может не быть, а в объекте - могут быть.

**Comment by simufkwikler02** [comment]
То есть в классе CompositeValidator нужно создать дополнительные public методы, которые могли бы проверять данные по одному?
Но классы валидации всё равно принимают только целую запись.

**Comment by alexander-rykov** [comment]
в интерфейсе IRecordValidator есть же методы для валидации

public bool ValidateParametrsFirstName(string input);

public bool ValidateParametrsLastName(string input);

и т.тд.

**Comment by simufkwikler02** [comment]
В том то и дело, что нету. В IRecordValidator есть только метод ValidateParametrs. И он принимает целую запись.
А все остальные классы валидаторы реализуют этот интерфейс. То есть в классе  CompositeValidator есть только один метод, который проверяет запись целиком.
