### ISSUE TITLE
Шаг 12 : Применение итератора

### ISSUE THREAD

**Issue by simufkwikler02** [epam-dotnet-lab/file-cabinet-task#105]
Хотел уточнить несколько вопросов
1) В качестве коллекции в FileSystemIterator мы должны хранить смещения?
2) Мы должны везде теперь, где раньше было ReadOnlyCollection<FileCabinetRecord> использовать IRecordIterator? и писать новый код, что бы получать из них записи? Потому что если Find возвращает IRecordIterator, то и, например, наш printer должен уметь читать IRecordIterator, а значит все методы должны посылать в printer IRecordIterator.
3)  В других вопросах писалось "итератор должен "вычислять" последовательность (то есть формировать результирующий список) в "ленивом" режиме, то есть загружать только одну запись на каждой итерации.", но у нас и так результирующий список в методе find вычислялся, в следствии загрузки записей по одной, пока не получится итоговый список. Или имеется в виду, что итератор должен вычислять элементы из списка в любом месте программы(или создать этот список), только когда мы ему это скажем?

**Comment by alexander-rykov** [comment]
_"В качестве коллекции в FileSystemIterator мы должны хранить смещения?"_ - нет, позиция следующей записи должна вычислятся каждый раз при обращении к итератору.

_Мы должны везде теперь, где раньше было ReadOnlyCollection использовать IRecordIterator?_ - в интерфейсе IFileCabinetService есть три метода Find, они должны возвращать IRecordIterator. Затем итератор должен быть заменен на  IEnumerable<T>/IEnumerator<T>.

_Или имеется в виду, что итератор должен вычислять элементы из списка в любом месте программы(или создать этот список), только когда мы ему это скажем?_ - да, под вычислением здесь имеется ввиду вычисление позиции следующей записи и ее последующее чтение.
