### ISSUE TITLE
Шаг 15: Предупреждения

### ISSUE THREAD

**Issue by simufkwikler02** [epam-dotnet-lab/file-cabinet-task#106]
Здравствуйте, такой вопрос, предупреждения SA1011 и SA1018 конфликтуют на такой записи как string[]?
один просит поставить пробел string[] ?
а другой просит убрать пробел string[]?
Можно отключить или подавить это предупреждение? и вообще все последующие такого рода предупреждения, связанные с пробелами, если они будут мешать подобным образом?

**Comment by alexander-rykov** [comment]
можно подавить SA1011 прагмой, но посмотрите, действительно ли вам нужен null в этом массиве

**Comment by simufkwikler02** [comment]
Спасибо
