### ISSUE TITLE
Code review : неэквивалентное преобразование кода

### ISSUE THREAD

**Issue by ffje** [epam-dotnet-lab/file-cabinet-task#12]
Последнее преобразование кода в [code review](https://github.com/epam-dotnet-lab/file-cabinet-task/tree/master/code-review)  неэквивалентно. 

### string.IsNullOrEmpty

Вместо:

```cs
if (firstName.Trim() == string.Empty) { }
```

Нужно:

```cs
if (string.IsNullOrEmpty(firstName)) { }
```
Дело в том, что, например, при входных данных firstName = "        " первый вариант кода(где используется Trim() и сравнение с string.Empty) даст результат true, в то время как string.IsNullOrEmpty даст false(строка, состоящая из пробелов не является ни пустой, ни нулевой ссылкой).

**Comment by alexander-rykov** [comment]
спасибо. заменил на string.IsNullOrWhiteSpace:
https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=netframework-4.8
