### ISSUE TITLE
Шаг 7: Кеширование записей

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#13]
Должны ли записи кэшироваться в словари в FileCabinetFilesystemService при запуске приложения? Или же поиск по имени/дате производить в бинарном файле?

**Comment by alexander-rykov** [comment]
@vitalmizevich такого требования нет,  подобное поведение ([разогрев кэша](https://stackoverflow.com/questions/22756092/what-does-it-mean-by-cold-cache-and-warm-cache-concept)) выглядит неплохо. иначе первый поиск будет работать перебором.
