### ISSUE TITLE
Шаг <8>: <параметры командной строки>

### ISSUE THREAD

**Issue by Shenn2948** [epam-dotnet-lab/file-cabinet-task#14]
![image](https://user-images.githubusercontent.com/41282278/67290537-e7cbe480-f4e8-11e9-927e-5aac99f057bd.png)

Есть ли впринципе возможность передать аргументы командной строки с одинарным backslash как в примере в задании? Если как в примере вводить такой одинарный backslash - они не распознаются по понятным причинам. Если нельзя, тогда придется заставить вводить два, считая это невалидным вводом.

**Comment by alexander-rykov** [comment]
1. в windows используется backslash, в unit системах - slash.

2. вы используете bash через mingw, поэтому вам нужно использовать slash. если вы начнете использовать cmd.exe, то вам будет нужно использовать backslash.
