### ISSUE TITLE
Шаг 10: не получается цепочка вызовов для ValidatorBuilder в пункте 5.

### ISSUE THREAD

**Issue by ffje** [epam-dotnet-lab/file-cabinet-task#15]
Пример использования _ValidatorBuilder_:

```cs
var validator = new ValidatorBuilder()
    .ValidateFirstName(min, max)
    .ValidateLastName(min, max)
    .ValidateDateOfBirth(from, to)
    .Create();
```
Дело в том, что исходя из UML-диаграммы, методы ValidateFirstName, ValidateLastName(etc.) не возвращают ничего(тип void). После вызова метода ValidateFirstName вызов второго метода будет невозможен, так как тип, который мы получили после вызова - void.

Кажется, для того, чтобы реализовать такой синтаксис стоило бы в методах Validate... сделать тип возвращаемого значения ValidatorBuilder, а внутри них после обработки основной логики вызывать return this.

**Comment by alexander-rykov** [comment]
@ffje возвращаемое значение на диаграмме не указано, поэтому задайте такое, какое необходимо.
