### ISSUE TITLE
Шаг 9: Статистика удаленных записей

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#16]
Количество удаленных записей в FileCabinetFilesystemService должно обнуляться после команды purge или же показывать общее количество за все время существования сервиса, с момента создания файловой структуры? Если второй вариант, то для FileCabinetMemoryService такая статистика должна быть реализована тоже.

**Comment by alexander-rykov** [comment]
@vitalmizevich да, должно обнулятся, так как для этого сервиса требуется показать количество записей с установленными битом _IsDeleted_. [Обновил описание](https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/step09.md#%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B0-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9).
