### ISSUE TITLE
Шаг 2..9 : ID

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#17]
Возние еще вопрос: ID - это у нас уникальныое значение или же это просто порядковый номер? Т.к. в файле для импорта могут находиться данные в несортированном виде (пример порядка записей: 4,3,16,33,54) и данные, по-факту, являются валидными и должны быть импортированы с такими же значениями, что и в исходном файле.

Конкретная проблема возникает в производительности (в частности с FileCabinetFilesystemService). А имменно, во время импорта нужно проверить существует ли данный id, удалена ли запись с данным id (установлен флаг удаления), после этого, если запись существует, обновить данные с данным id. Если запись не существует, то создаем запись с данным id, импортированным из файла.

Теперь, если вернуться к вопросу уникальности, появляется еще одна проблема - нам нужен генератор id т.к. у нас id это интовое значение, и после импорта (если алгоритм получения нового id основан на количестве записей), во время добавления новой записи может возникнуть коллизия, из чего следует, что изначально при генерации id нужно проверить существующие и выделить свободный номер из положительного диапазона int.

Все эти постоянные проверки в фале начинают влиять на производительность при импорте.

**Comment by alexander-rykov** [comment]
@vitalmizevich 

_Возние еще вопрос: ID - это у нас уникальныое значение или же это просто порядковый номер?_

уникальное значение, в сервисе записи могут храниться в неупорядоченном виде.

_Т.к. в файле для импорта могут находиться данные в несортированном виде (пример порядка записей: 4,3,16,33,54) и данные, по-факту, являются валидными и должны быть импортированы с такими же значениями, что и в исходном файле._

да, если в файле импорта находятся несортированные записи это норма.

_Конкретная проблема возникает в производительности (в частности с FileCabinetFilesystemService). А имменно, во время импорта нужно проверить существует ли данный id, удалена ли запись с данным id (установлен флаг удаления), после этого, если запись существует, обновить данные с данным id. Если запись не существует, то создаем запись с данным id, импортированным из файла._

в файле данных:
* должна быть только одна активная неудаленная запись с конкретным ID.
* может быть несколько записей с конкретным ID, если для них установлен бит удаления.

т.е. сервис должен игнорировать удаленные записи.

_Теперь, если вернуться к вопросу уникальности, появляется еще одна проблема - нам нужен генератор id т.к. у нас id это интовое значение, и после импорта (если алгоритм получения нового id основан на количестве записей), во время добавления новой записи может возникнуть коллизия, из чего следует, что изначально при генерации id нужно проверить существующие и выделить свободный номер из положительного диапазона int._

у вас в файле импорта должен быть ID записи, его и берите. генерация нового ID при добавлении - это другая задача. можно использовать max(ID) + 1.

**Comment by vitalmizevich** [comment]
Но проблема в том, что не сказано, что записи в файле находятся последовательно.
Допустим у нас есть FileCabinetFilesystemService с записями 100,200,300,400,500,600,700,800,900,1000.

Мы удаляем 100,200,300,400,500 и 900. Остаются 600, 700, 800, 1000. (остальные как бы есть, но они не видны, т.к. помечены битом удаления). Теперь импортируем файл с записями от 1 до 500. Тогда структура файла имеет вид 600, 700, 800, 1000, 1, 2 ... 500.

Если мы будем генерировать по алгоритму max(ID) + 1, то следующий номер получается 1001. Но может быть ситуация, когда max = int.MaxValue, а значит мы не сможем сгенерировать новую запись с корректным id. Я нашел 2 варианта решения проблемы. Либо нам нужно создать дополнительный словарь для id (кэш) и использовать последовательный алгоритм генерации id (начинаем с 1) с проследующей проверкой в кэше (если в кэше есть 1, то увеличиваем значение, если опять есть значение, то опять увеличиваем значение и так до тех пор, пока не появится свободное), либо же проверять значения напрямую а файле т.е. каждый раз с увеличением значения генерироваемого id на 1 нужно от начала до конца прочитать значение всех id (удаленные читаются тоже, но так как установлени бит удаления,  то id является уникальным) в файле и вернуть булевское значение указывающее, является id уникальным или нет.  

Теперь же, когда записи у нас находятся не последовательно в бд, то во время добавления нам нужно определить есть ли запись с таким id, для того чтобы обновить ее, или же если нету, то создать новую. Когда записей около 10 и импортирыем тоже около 10, то все происходит быстро, но когда записей уже больше 100, то с каждой новой добавленной записью у нас увеличивается пространство и для проверки (чтение файла от начала и до конца), чтобы обновить или добавить новую запись. 

Попытка добавления сортировки записей в файле не решит проблему, т.к. между id может быть промежуток, как в примере выше (было 600, 700, 800, 1000, 1, 2 ... 500, стало 1, 2 ... 500, 600, 700, 800, 1000 - id не увеличивается на 1 каждый раз, а идут в разнобой, но по-порядку), к тому же реализация команды потребует предварительное использование purge и дальнейшее усложнение.

Я реализовал добавление записей с реализацией "уникальности" id с последовательным чтением через файл. Но проблема в производительности, за 30 мин импортировалось всего 900 записей, и с увеличением количества увеличевается прямопропорционально время.

Суть написанного мной можно свести вот к чему: в ответе на вопрос https://github.com/epam-dotnet-lab/file-cabinet-task/issues/10 вы писали про "требования" и то что это «нечто такое, что определяет выбор дизайна». Поэтму какие конкретные требования в данном случае, приложение должно работать корректно, но с сильным ущербом производительности или быстро, но с сильной вероятностью испортить входные данные (что в случае неуникальности  id и будет).

**Comment by alexander-rykov** [comment]
@vitalmizevich 

_Но может быть ситуация, когда max = int.MaxValue, а значит мы не сможем сгенерировать новую запись с корректным id._

MaxValue для int - 2,147,483,647. для наших целей - вполне достаточно. если уж совсем "мало", замените int на long. :)

_либо же проверять значения напрямую а файле т.е. каждый раз_

пожалуй, проходить по всему файлу данных при добавлении новой записи это совсем неоптимальный вариант. вам никто не запрещает хранить дополнительные данные в сервисе, чтобы ускорить операцию добавления.

_Я реализовал добавление записей с реализацией "уникальности" id с последовательным чтением через файл. Но проблема в производительности, за 30 мин импортировалось всего 900 записей, и с увеличением количества увеличевается прямопропорционально время._

согласен. это решение - не оптимальное. теперь придумайте оптимальное :)

**Comment by alexander-rykov** [comment]
@vitalmizevich 

_Поэтму какие конкретные требования в данном случае, приложение должно работать корректно, но с сильным ущербом производительности или быстро, но с сильной вероятностью испортить входные данные (что в случае неуникальности id и будет)._

ID - уникальное значение. я не вижу больших проблем сделать добавление O(log N) ... O(1). чтобы и быстро, надежно.

**Comment by vitalmizevich** [comment]
Оптимизировал алгоритм удаления, теперь он основывается на кэше (словарь существуюших записей где ключ - id, значение - position in file, и словарь удаленных записей, основанный на таком же принципе). Импорт 10.000 записей (точнее даже перезапись сществуюших) за несколько минут является оптимальным решением?

**Comment by alexander-rykov** [comment]
@vitalmizevich неплохо.
