### ISSUE TITLE
Шаг 11: Нужно ли добавлять возможность совместной работы логгера и таймера? Должны ли логгироваться(журналироваться??) исключения?

### ISSUE THREAD

**Issue by ffje** [epam-dotnet-lab/file-cabinet-task#18]

**Comment by alexander-rykov** [comment]
@ffje 

1) "Нужно ли добавлять возможность совместной работы логгера и таймера?"

см. соответствующую [диаграмму последовательности](https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/images/step11-logger-decorator-sequence.png).

2) "Должны ли логгироваться(журналироваться??) исключения?"

разумеется.
