### ISSUE TITLE
Шаг 10: диаграмма классов

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#19]
AppCommandRequest имеет два свойства только на get, а в методе Program класса Main мы во время создания экземпляра класса AppCommandRequest пытаемся присвоить значения полям не через конструктор, а напрямую, чего сделать никак не сможем.

![image](https://user-images.githubusercontent.com/20145590/67518428-7a1ce580-f6ad-11e9-99f8-ff262a28a7f9.png)

**Comment by alexander-rykov** [comment]
@vitalmizevich добавьте конструктор или сеттер, не принципиально.
