### ISSUE TITLE
Шаг 11: конфигурационный файл

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#20]
Где должен находиться конфигурационный файл validation-rules.json?
Проблема в том, что если  он должен лежать в корне проекта, то использовать   Environment.CurrentDirectory или Directory.GetCurrentDirectory() не получиться, т.к. во время работы генератора (FileCabinetGenerator) будут получаться совершенно другие значения. Явно указать путь - это тоже проблема, мы не сможем запустить приложение, если переименуем директорию. Можете подсказать возможные пути решения этой проблемы? Сбиндить данные получилось.

**Comment by SvetlanaSavich** [comment]
в настройках validation-rules.json нужно выбрать Copy Always для Copy to Output Directory?

**Comment by alexander-rykov** [comment]
@vitalmizevich - в csproj можно задать параметр для файла - копирование в output binary каталог.

копировать всегда
```
  <ItemGroup>
    <None Update="readme.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```
копировать только новый файлы:
```
  <ItemGroup>
    <None Update="readme.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```
Это поведение можно редактировать в VS на закладке Properties для файлов - "Copy to output directory".
