### ISSUE TITLE
Шаг 13: интерпретация команды select

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#21]
В задании первый пример использования команды select интерпретируется неправильно, в данном случае было бы логично использовать 'or' т.к. 'and' вносит строгое соответствие относительно каждого критерия, в нашем случае должно быть 0 записей, потому что firstname одновременно не может быть John и Stan (John != Stan).
> select id, firstname, lastname where firstname = 'John' and firstname = 'Stan'

**Comment by alexander-rykov** [comment]
@vitalmizevich да, все верно - нужно OR.
