### ISSUE TITLE
Шаг 13: Команда insert

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#22]
В задании с реализацией команды select, мы передаем данные в сервис, где в команде указываем сразу id. По идее, мы не должны его указываеть, так как нам тогда требуется расширить интерфейс добавления данных. Здесь возникает и второй вопрос, команда insert должна принимать перечень всех полей или нет? Если нет, то какое поведение должно ожидаться, т.к. в нашем случае, валидатор не пропустит эти данные их-за своих правил.

> insert (id, firstname, lastname, dateofbirth) values ('1', 'John', 'Doe', '5/18/1986')

**Comment by alexander-rykov** [comment]
@vitalmizevich 

1) "По идее, мы не должны его указываеть, так как нам тогда требуется расширить интерфейс добавления данных."

если нужно, расширяйте интерфейс сервиса. реализация полностью на вас.

2) "Здесь возникает и второй вопрос, команда insert должна принимать перечень всех полей или нет?"

да, всех полей, но они могут идти в произвольном порядке.
