### ISSUE TITLE
Шаг 14:  Мемоизация

### ISSUE THREAD

**Issue by ffje** [epam-dotnet-lab/file-cabinet-task#25]
Предполагалось ли то, что реализация новых команд(select, update, insert, etc) должна ложиться на каждый отдельный тип сервиса, и, соответственно, новые методы должны быть помещены в интерфейс IFileCabinetService?

Логично предположить, что работа сложны методов по типу select не должна зависеть от конкретного сервиса, а должна компоноваться из "базового" набора возможностей IFileCabinetService(то есть реализовав минимальный набор команд типа create, remove, findby... мы получаем возможность табличного вывода, удобной семантики update, insert, и pattern matching с where, что, кажется, является большим плюсом). В этом случае мы убираем прямую возможность использования старых(list, remove, findby... , etc) команд из консоли и применяем их непосредственно внутри новых команд на слое выше. При такой архитектуре получается, что реализация мемоизации на уровне FileCabinetMemoryService не имеет смысла, потому что часть данных уже хранится в словарях, доступ к которым обеспечивается за О(1). Для того, чтобы все-таки реализовать мемоизацию на слое "повыше" придется компоновать новые команды в одну сущность, что сделает код более связным.

В случае же помещения новых команд внутрь интерфейса IFileCabinetService фактически придется дублировать логику внутри каждого из сервисов(и кроме этого переписывать большое количество кода), что тоже звучит плохо. Как лучше поступить?

**Comment by vitalmizevich** [comment]
Могу ошибаться, так как до конца не понял смысл мемоизации в задании (или же правильно, если это обычное кэширование в словарь), но в данном случае похоже на то, что нужно расширить интерфейс сервиса, чтобы метод GetRecords() мог принимать какой-то фильтр (для получения всех записей опционально должен быть нулевый), чтобы в дальнейшем на его основе сформировать ключ (связан с запросом фильтрации) и список записей для словаря, из этого следует, что при повторном запросе записей из сервиса с таким же фильтром, мы не пробегаем весь список, а забираем только  "закэшированные" (по большому счету, это все требуется для принтера, выводящего записи на экран).

Если мои рассуждения выше относительно правильные, то возникает другой вопрос:
Если мы пишем два логически одинаковых фильтра, но синтаксически разных (пример: where firstname = 'John ' or lastname = 'Doe' и where lastname = 'Doe' or firstname = 'John '), то если в качестве ключа брать комбинацию слов-токенов (FIRSTNAMEJOHNORLASTNAMEDOE 
и LASTNAMEDOEORFIRSTNAMEJOHN),  мы кэшируем два разных запроса, хотя их считать можно как один. Нужно ли как-то решать такого рода проблему?

**Comment by alexander-rykov** [comment]
@ffje 1) мемоизацию можно добавить только для одного сервиса и реализовать ее на уровне самого сервиса. это просто и позволит познакомиться с коцепцией.

реализовать мемоизацию на уровень выше может быть проблематично - посмотрите на filesystem сервис. что вы будете мемоизировать? итератор?

2) расширяйте интерфейс сервиса, если это необходимо.

**Comment by alexander-rykov** [comment]
@vitalmizevich "в данном случае похоже на то, что нужно расширить интерфейс сервиса, чтобы метод GetRecords() мог принимать какой-то фильтр"

вы вправе изменять публичный API класса / интерфейса.

"а забираем только "закэшированные"

верно.

"мы кэшируем два разных запроса, хотя их считать можно как один. Нужно ли как-то решать такого рода проблему?"

очень хорошо, что вы заметили эту проблему. решайте, если придумаете как.
