### ISSUE TITLE
Шаг 7: отображение данных

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#27]
Данные в файловый сервис мы можем добавлять в режимах custom и default с разными правилами валидации.  Если добавить данные в режиме default, а запустить приложение с режимом custom, то на консоль будут выводиться невалидные данные. Требуется ли чтобы в режиме custom отбражались записи соответствующие этому режиму, а в режиме default только подходящие под default валидацию? Плюс как считать количество записей в сервисе (для каждого режима выводить только свое количество записей)?

**Comment by alexander-rykov** [comment]
1) Валидация применяется при добавлении записей, выводить все данные независимо от режима валидации.

2) В целом будем считать, что сервис может работать только в одном из режимов, поэтому переключение режима для сервиса, который уже имеет загруженные данные, рассматривать не будем.
