### ISSUE TITLE
Использование tuples в интерфейсах

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#28]
Нормально ли использовать ValueTuple в качестве возвращаемого значения в методах интерфейсов (в классах) или лучше завести для этого отдельный класс/структуру?

**Comment by alexander-rykov** [comment]
заменил ValueTuple на tuples в заголовке

есть несколько соображений против использования кортежей в публичных API подсистем.

1) У типа Tuple<T1, T2, ...> внутренние члены имеют бессмысленные имена Item1, Item2,...

Это затрудняет чтение и понимание кода, увеличивает вероятность ошибки, особенно, когда кортеж содержит одинаковые типы.

var t = new Tuple<int, int, int>(age, length, velocity);
...
var age = t.Item2;
var length = t.Item3;
var velocity = t.Item1;

Для value tuples это возражение не актуально + есть удобный deconstruct.

_Returning strongly typed Tuple<> instances as part of a public API for a public type is rarely a good idea. As you yourself recognize, tuples requires the parties involved (library author, library user) to agree ahead of time on the purpose and interpretation of the tuple types being used. It's challenging enough to create APIs that are intuitive and clear, using Tuple<> publicly only obscures the intent and behavior of the API._
https://stackoverflow.com/questions/3017352/is-using-net-4-0-tuples-in-my-c-sharp-code-a-poor-design-decision

2) Плохая устойчивость к изменениям. Этот недостаток характерен для всех tuples.

Например, у вас есть интерфейс IMyInterface, который широко используется в вашем приложении.

public interface IMyInterface {
  (int age, int children) DoSomething();
}

Вам потребовалось расширить кортеж, вы добавили новый элемент.

public interface IMyInterface {
  (int age, int temperature, int children) DoSomething();
}

Это приведет к тому, что код вашего приложения сломается в неожиданных местах. Например, в том месте, где вы передаете его в какой-нибудь метод.

public void Process() {
    var t = this.myInterface.DoSomething();
    Print(t);
}

public void Print((int age, children) t) {}

3) Минус строгая типизация - компилятор не будет предупреждать об ошибках:

public void Print((int age, children) t) {}

var age = 23;
var children = 2;

Print((age, children));
Print((children, age));
