### ISSUE TITLE
Шаг 02: Создание сервиса FileCabinetService

### ISSUE THREAD

**Issue by AndreiValuika** [epam-dotnet-lab/file-cabinet-task#29]
Добрый день. Пропустил один коммит. **"Add implementation for list command"**. Откатываться и переделывать или не критично?

**Comment by alexander-rykov** [comment]
не ясно, где вы пропустили коммит - в мастере или ветке шага, успели ли залить ветку в мастер и т.д.

переделайте. для полного отката можно использовать команду git reset.
https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%A0%D0%B0%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D1%82%D0%B0%D0%B9%D0%BD-reset

для отмены ИЗМЕНЕНИЙ можно воспользоваться git revert.
