### ISSUE TITLE
Шаг 5: Валидаторы для сервиса и ввода

### ISSUE THREAD

**Issue by alexander-rykov** [epam-dotnet-lab/file-cabinet-task#3]
Можете разъяснить последний пункт [шага 5](https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/step05.md).

Вопрос в частности в валидаторах. Сказано, что нужно " дописать необходимые конвертеры и валидаторы", так а что делать с валидатором в FileCabinetService? Он же будет дублировать все тоже самое. Получается, что в FileCabinetService удалить повторную валидацию, оставив только получаемую из делегатов? Тогда получается,что не нужно внедрять зависимость IValidator в сервис и сами имплементации валидаторов

**Comment by alexander-rykov** [comment]
Эти валидаторы имеют различное назначение:
* валидаторы ввода проверяют соответствие ВВОДА пользователя заданным критериям.
* валидаторы в сервиса проверяют ДАННЫЕ, которые "клиент" сервиса передают сервису.

В данном случае наличие двух одинаковых проверок выглядит излишним, но представьте ситуацию, когда ввод данных и отправка их в сервис не связаны друг с другом или отделены друг от друга. Например, приложение получает данные не с консоли, а через сеть. Или код ввода данных отправляет данные не в сервис, а в очередь сообщений.

Ответ на ваш вопрос:

_Получается, что в FileCabinetService удалить повторную валидацию, оставив только получаемую из делегатов?_

Нет, удалять не нужно.

_Тогда получается,что не нужно внедрять зависимость IValidator в сервис и сами имплементации валидаторов_

Внедрять нужно.

С дубликацией кода разберемся позже.

**Comment by vitalmizevich** [comment]
Объясните, где должны находиться конвертеры-делегаты и валидаторы-делегаты, и что подразумевается под "Измените функциональность валидации входных данных таким образом, чтобы применение правил валидации зависело от параметра validation-rules.", если уже одна стратегия валидации используется в таком ключе?

**Comment by alexander-rykov** [comment]
@vitalmizevich 

> Дублирование одной и той же валидации считается нормой?

Наивный ответ на Ваш вопрос - дублирование кода это неприемлимо, всегда применяйте принцип DRY.

Более осторожный ответ на Ваш вопрос - в большинстве случаев дублирование кода можно безболезненно устранить, однако сложность изменения кода и требуемый подход зависит от ситуации.

Например, в Ваше предложение состояло в том, чтобы в принципе лишить сервис *возможности* проверки входных параметров:

_Получается, что в FileCabinetService удалить повторную валидацию, оставив только получаемую из делегатов?_

Т.о. вместо изменения структуры кода при сохранении прежнего поведения Вы предлагаете изменение *функциональное*, которое приведет совершенно иному поведению класса сервиса. Это качественное изменение, которое объективно *ухудшает* возможности сервиса.

Приведу цитату из [статьи вики](https://en.wikipedia.org/wiki/Duplicate_code):

_Even code sequences that are only functionally identical may be considered duplicate code._

То есть дублирующий код это функционально идентичный код.

_On the other hand, if one copy of the code is being used for different purposes, and it is not properly documented, there is a danger that it will be updated for one purpose, but this update will not be required or appropriate to its other purposes._

В этой цитате речь идет о том, что важен не только сам факт наличия дублирующего кода, но и контекст его. При изменении одного контекста может потребоваться изменение в общем коде, однако для другого контекста эти изменения могут быть губительны.

Еще [мнение](https://www.quora.com/When-is-code-duplication-okay):

_However, that popular advice — move it to a method — should not be applied blindly. Sometimes two lines only appear to be the same. That is, while the code is functionally identical, it may be semantically different._

Речь идет не о механическом сравнивании двух участков кода, но и о его смысле - в каком контексте этот код работает.

_When deciding to remove duplication, you have to consider the meaning of the code as well as its structure. If the code changes, the change should apply to everything that depends on it, without exception._

Соглашусь с мнением - [Code duplication is acceptable when it makes the intent of a test clearer](https://hackernoon.com/when-code-duplication-is-acceptable-51ce33ecd0f5). Тесты с дублирующим кодом часто выглядят более понятными, чем отрефакторенные в соответствии с принципом DRY.

И еще - [Code duplication anti-pattern, Diagnosis and remediation](https://medium.com/@kooliahmd/code-duplication-anti-pattern-diagnosis-and-treatment-44f8c1555382):

_Duplicated code is evil, will slow down developers and increase the chance of software breakdown, however blindly escaping from it will make things even worse, and in most cases we end up with extra parameters passed to methods, if/else statements and testing on object instances type. all of this symptoms can be the result of a wrongly duplicated code refactor._

Итог. В вашем коде действительно есть дублирование кода. Однако, дублирование не самого факта проверки, а дублирование кода правил проверок.

В будущем мы это дублирование попробуем исправить.

**Comment by alexander-rykov** [comment]
@vitalmizevich 

_Объясните, где должны находиться конвертеры-делегаты и валидаторы-делегаты_

В том месте, которое Вы посчитаете самым подходящим.

_что подразумевается под "Измените функциональность валидации входных данных таким образом, чтобы применение правил валидации зависело от параметра validation-rules.", если уже одна стратегия валидации используется в таком ключе?

Необходимо сделать так, чтобы параметр командной строки validation-rules влиял и на критерии проверки входных параметров, и на критерии валидации данных в классе.
