### ISSUE TITLE
Шаг 03: warning CA1062: validate parameter 'lastName' is non-null before using it.

### ISSUE THREAD

**Issue by Tork2048** [epam-dotnet-lab/file-cabinet-task#30]
Можно ли игнорировать/отключить это предупреждение?
У меня есть метод ValidateValue (+ перегрузки) в который я передаю переменную и параметры валидации. В том числе метод проверяет на null. Переменные в него передаю, естественно, без проверок.
Я могу, конечно, написать бесполезную условную конструкцию чтобы убрать предупреждение.

**Comment by alexander-rykov** [comment]
[CA1062: Validate arguments of public methods](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019)

_**When to suppress warnings**
You can suppress a warning from this rule if you are sure that the dereferenced parameter has been validated by another method call in the function._
