### ISSUE TITLE
Шаг 3-4: Вывод команды 'help' для команд с параметрами

### ISSUE THREAD

**Issue by ArtemGorodk01** [epam-dotnet-lab/file-cabinet-task#32]
Что должна отображать команда 'help' для команд с параметрами, таких как 'edit' и 'find'?
Нужно ли описывать параметры в короткой и подробной справке по команде?

**Comment by alexander-rykov** [comment]
1) короткая справка - краткое описание команды.
2) подробная справка - расширенное описание, допустимо вставить в нее описание параметров, примеры и проч.
