### ISSUE TITLE
Шаг <05>: Параметр командной строки

### ISSUE THREAD

**Issue by AndreiValuika** [epam-dotnet-lab/file-cabinet-task#33]
"Добавьте параметр командной строки приложения с помощью которого можно указать тип правил проверки."
Вопрос. Разбирать параметры "вручную" или можно использовать готовые библиотеки (например FluentCommandLineParser или Microsoft.Extensions.CommandLineUtils) ?

**Comment by alexander-rykov** [comment]
См. [Step 1](https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/step01.md):

"Внимание! Использование внешних пакетов nuget допускается только в случае, если это предусмотрено руководством, или по согласованию с тренером или ментором."
