### ISSUE TITLE
Шаг <7>: <3.Реализуйте метод FileCabinetFilesystemService.CreateRecord, который должен записывать переданные ему данные в файл данных.>

### ISSUE THREAD

**Issue by VadimOliseichik** [epam-dotnet-lab/file-cabinet-task#34]
Здравствуйте.
Скажите, пожалуйста : с помощью чего заполнять файл с расширением .db? 
С помощью SQL-команд ? 
Или же это обычный бинарный файл с таким названием (BinaryReader и BinaryWriter)?

**Comment by alexander-rykov** [comment]
Это бинарный файл, в котором располагаются записи фиксированного размера.

[Step 07](https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/step07.md):

_Реализуйте метод FileCabinetFilesystemService.CreateRecord, который должен записывать переданные ему данные в файл данных. Записи должны добавляться в файл последовательно, размер записи должен быть фиксированным._
