### ISSUE TITLE
Шаг 05: Включите (Warning) предупреждение для правила SA1600

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/file-cabinet-task#35]
После включения правила SA1600(через VisualStudio) у меня включилось также CA1303("не следует передавать литералы в виде локализованных параметров"). Так и должно быть? Или CA1303 можно отключить обратно?
Ибо правило очень жесткое...

**Comment by alexander-rykov** [comment]
можно использовать ResourceManager как показано в примере - https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1303?view=vs-2019.

получится приложение с возможностью локализации.

**Comment by MaksimPrudnikau** [comment]
@alexander-rykov 
Использую ResourceManager, как в примере

```
var resourceManager = new ResourceManager("en-US", Assembly.GetExecutingAssembly());
 
 Console.Write(resourceManager.GetString("First name: ", CultureInfo.CurrentUICulture));
```
В логе
```
Unhandled exception. System.Resources.MissingManifestResourceException:
Could not find the resource "en-US.resources" among the resources "" embedded in the assembly "FileCabinetApp",
nor among the resources in any satellite assemblies for the specified culture. 
 Perhaps the resources were embedded with an incorrect name.
```

**Comment by alexander-rykov** [comment]
@MaksimPrudnikau по каким-то причинам у вас нет в приложении встроенного ресурса для языка en-US.

первый параметр конструктора (ResourceManager("en-US", ) это не культура, а baseName

в примере вот так:

ResourceManager rm = new ResourceManager("ExampleResources", typeof(Example).Assembly);
string greeting = rm.GetString("Greeting");

**Comment by MaksimPrudnikau** [comment]
> @MaksimPrudnikau по каким-то причинам у вас нет в приложении встроенного ресурса для языка en-US.
> 
> первый параметр конструктора (ResourceManager("en-US", ) это не культура, а baseName
> 
> в примере вот так:
> 
> ResourceManager rm = new ResourceManager("ExampleResources", typeof(Example).Assembly);
> string greeting = rm.GetString("Greeting");

Значит мне нужно создать свой собственный ресурс и пользоваться им?
