### ISSUE TITLE
Шаг 06: "export csv"

### ISSUE THREAD

**Issue by AndreiValuika** [epam-dotnet-lab/file-cabinet-task#36]
В первом задании:
"Реализуйте команду "export csv", которая должна экспортировать данные сервиса в файл формата CSV." 
"Export csv" написано, как имя команды. Но в примере и на диаграмме это команда "export" с параметром "csv". В втором задании ситуация аналогичная. Реализовывать надо как одну команду с разными параметрами, две совершенно разные команды или на свое усмотрение (я слишком буквально понимаю задания )?

**Comment by alexander-rykov** [comment]
реализуйте команду "export" с параметром "csv".
