### ISSUE TITLE
Шаг 06: Экспорт в CSV

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/file-cabinet-task#37]
На диаграмме классов метод "MakeSnaphot() : FileCabinetServiceSnapshot" присутствует как в классе FileCabinetService так и в FileCabinetServiceSnapshot. Так и надо?
Непонятно зачем он в FileCabinetServiceSnapshot. В паттерн Memento не совсем укладывается. Make наверное только FileCabinetService должен делать, а FileCabinetServiceSnapshot только Get (если понадобится).

**Comment by alexander-rykov** [comment]
верно, в диаграмме ошибка. исправил.
