### ISSUE TITLE
Шаг 6: Реализация паттерна "Снимок".

### ISSUE THREAD

**Issue by Tork2048** [epam-dotnet-lab/file-cabinet-task#39]
В диаграмме классов пункта "Экспорт в CSV" метод MakeSnapShot() возвращает объект типа FileCabinetServiceSnapshot.
Паттерн "снимок" предлагает использовать класс "снимок", как вложенный в классе создателя, т.е. FileCabinetService. Создатель при этом возвращает ограниченную интерфейсную ссылку на объект снимка, предоставляющую доступ к набору методов, требумых опекунам.

Я хочу полностью скрыть класс FileCabinetServiceSnapShot. Могу ли я выполнить задание так, как предлагает паттерн?

**Comment by alexander-rykov** [comment]
1) Основная задача шаблона - сохранение/восстановление состояния. Необходимость обеспечения дополнительных условий ("защит") самого хранителя не является обязательной.

см. ["Классический вариант" структуры ](https://ru.wikipedia.org/wiki/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)) и [код для этого варианта](https://ru.wikipedia.org/wiki/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)#%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82_%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0_%D0%A1#).

2) "Я хочу полностью скрыть класс FileCabinetServiceSnapShot"

a) ["Реализация с пустым промежуточным интерфейсом"](https://refactoring.guru/ru/design-patterns/memento)
b) абстрактный класс для хранителя.
