### ISSUE TITLE
Шаг 5: Рефакторинг параметров

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#4]
Методы FileCabinetService.CreateRecord и FileCabinetService.EditRecord принимают много аргументов. Подумайте над недостатками такого подхода. Примените технику Introduce Parameter Object.

Нормально ли передавать сразу в эти методы FileCabinetRecord?

**Comment by alexander-rykov** [comment]
Для этого рефакторинга создайте отдельный класс.

**Comment by AleksandrZhadetsky** [comment]
на подобие EventArgs? я правильно понял суть?

**Comment by alexander-rykov** [comment]
@AlexanderZhadetskij 

_на подобие EventArgs? я правильно понял суть?_

да, правильно.

[Example 1: Event Args](http://principles-wiki.net/patterns:parameter_object)

_A typical usage of this pattern is the grouping of parameter in events. Some events carry large amounts of context data. Furthermore modifying the signature of an event causes large ripple effects as they are typically used on the interface to other subsystems, layers, etc. and there is an unknown and probably large amount of users of the event._
