### ISSUE TITLE
Шаг 7: валидация в FileCabinetFilesystemService

### ISSUE THREAD

**Issue by ArtemGorodk01** [epam-dotnet-lab/file-cabinet-task#41]
На диаграмме классов в первом пункте отображен конструктор для FileCabinetFilesystemService с одним параметром типа FileStream. Должен ли там быть ещё IRecordValidator. 
Если да, то могут быть разные режимы валидации, а значит и разная длина полей для firstName и lastName, следовательно разная структура файла. Если я правильно понимаю, то файл при новом запуске программы перезаписываться не должен. Таким образом, записав данные в файл в одном режиме валидации, работать с ним же при следующем запуске программы в другом  режиме валидации будет проблематично. Как быть в этой ситуации, выделять два разных файла или выделять место под строки "с запасом"?
Или всё проще и при каждом новом запуске программы файл перезаписывается?

**Comment by alexander-rykov** [comment]
_"Как быть в этой ситуации, выделять два разных файла или выделять место под строки "с запасом"?"_

Будем считать, что опция валидации доступна только для настройки приложения при первом запуске. Смену условий валидации после сохранения данных не рассматривать.
