### ISSUE TITLE
Шаг 07 :"валидация в FileCabinetFilesystemService" уточнения.

### ISSUE THREAD

**Issue by AndreiValuika** [epam-dotnet-lab/file-cabinet-task#42]
В предыдущем ответе Вы писали _"Будем считать, что опция валидации доступна только для настройки приложения при первом запуске. Смену условий валидации после сохранения данных не рассматривать."_ 
Но сервис принимая файловый поток при создании (второй и последующие разы), должен знать какая валидация применялась в первый раз. Может стоит изменить структуру файла и первый байт отвести под "флаг" Default/Custom валидации?

**Comment by alexander-rykov** [comment]
нет, не нужно. считайте, что правила валидации не меняются в процессе эксплуатации приложения. как в первый раз запустили, так и работает. не нужно усложнений :)
