### ISSUE TITLE
Шаг 9: бит IsDeleted в FilesystemService 

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/file-cabinet-task#43]
По поводу таблицы, описывающей место бита "IsDeleted".
Такое ощущение что она повернута на 90 градусов (по сравнению с таблицей в шаге 7), т.е. шапкой д.б. Bit / Name / Description.
Также, для чего зарезервированы биты 0-1 и 3-15? В дальнейших шагах про них никаких упоминаний не нашел.

Еще. Должна ли команда "purge" менять id записей? Например если есть записи с id 1, 2, 3 и запись 2 удалена, должен ли в записи 3 id поменяться на 2?
Просто в примере использования записи идут по порядку.

**Comment by alexander-rykov** [comment]
1) "Такое ощущение что она повернута на 90 градусов"

биты обычно отсчитываются справа. например, "0101" - 1й и 3й биты установлены, а 2й и 4й сброшены.

однако вы правы, такое расположение сбивает с толку. я переделаю.

2) " В дальнейших шагах про них никаких упоминаний не нашел." - пока не придумал, точнее есть идеи, но пока только идеи.

3)  "Должна ли команда "purge" менять id записей" - нет. id - это уникальный ключ записи, а не индекс в последовательности.

"Просто в примере использования записи идут по порядку." - возможно нужно исправить иллюстрацию, спасибо.
