### ISSUE TITLE
Шаг 11 : Применение ConfigurationBinder.Get для десериализации Json.

### ISSUE THREAD

**Issue by Tork2048** [epam-dotnet-lab/file-cabinet-task#44]
Приветствую!

Использую .Net Core 3.0
Через пакетный менеджер подключил в проект и использовал:
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.Binder;
using Microsoft.Extensions.Configuration.FileExtensions;
using Microsoft.Extensions.Configuration.Json;

Однако, следуя предоставленной документации:
https://garywoodfine.com/configuration-api-net-core-console-application/
компилятор не признает атрибуты сериализируемого класса или свойства, например:
[JsonObject("default")]
[JsonProperty("firstName")]
Подозреваю, это как-то связано с появлением встроенных библиотек в .NET Core 3.0:
System.Text.Json
System.Text.Json.Serialization
На данный момент использую их и все работает (немного другой синтаксис атрибутов, но в целом очень похоже на обычную сериализацию).

Допускается ли такая реализация загрузки конфигурации?
Спасибо.

**Comment by alexander-rykov** [comment]
Да, вполне.  В .NET Core 3 изменили API - https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/
