### ISSUE TITLE
Шаг 10: Валидация ввода после рефакторинга.

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/file-cabinet-task#45]
В Шаге 5 предлагается проводить валидацию каждой строки ввода (при добавлении / редактировании) с помощью метода ReadInput. И повторять ввод строки, пока она не будет валидной.
Однако в Шаге 10, после многочисленных рефакторингов это становится уже невозможно. Т.к. 1) у хэндлеров (CreateCommandHandler и пр.) вообще теряется доступ к валидатору, как к закрытому полю; 2) Даже если получить валидатор через сервис, то все равно открытым в нем остается только общий метод ValidateParameters, а частные методы, для построчной валидации, становятся скрытыми. Получается только проверить запись целиком, после ее окончательного ввода.
Как поступать? Отказываться от построчной валидации?

**Comment by alexander-rykov** [comment]
"вообще теряется доступ к валидатору, как к закрытому полю" - какое закрытое поле и у какого класса?

**Comment by idtitkov** [comment]
В шаге 5, после "Add constructor injection to FileCabinetService.", validator становится закрытым полем сервиса (ну и соответственно memory и file сервисов, которыми в последствии его заменяем) и передается ему через конструктор. Пока что все Ок, ведь он остается виден из Program, в т.ч. для обработчиков команд типа create/edit, т.к. они пока что тоже в Program.
Но в шаге 10, обработчики команд выносятся из Program в отдельные классы. И перестают видеть валидатор. И не расписано явно, как теперь для create/edit получить доступ к нему, для валидации данных на этапе ввода с консоли, т.е. ДО отправки в сервис. Можно многое самому додумать, но:
К концу шага 10, валидатор становится композитным и в нем остается только один открытый метод - ValidateParameters, который проверяет всю запись целиком. Судьба построчной валидации становится вообще неясной.
Не получается теперь, без костылей, забирать данные из консоли как предложено в Шаге 5:
```
Console.Write("First name: ");
var firstName = ReadInput(stringConverter, firstNameValidator);
```
Т.к. отдельно firstNameValidator (и прочие) брать неоткуда, они теперь инкапсулированы в одном, общем валидаторе, а валидатор инкапсулирован в сервисе.
Остается только для консольного ввода делать валидатор, не имеющий отношения к тому, который используют сервисы.
Ну или я на каком-то этапе что-то упустил)

**Comment by alexander-rykov** [comment]
"Ну или я на каком-то этапе что-то упустил)"

Вы упустили, что валидация ввода и валидация в сервисе это две разные валидации несмотря на общие правила. :)

**Comment by Tounderz** [comment]
Здравствуйте, Александр. Как я понял у нас происходит дублирование кода, валидация сервиса в случай чего выкидывает эксепшион? А валидация ввода запрашивает повторный ввод, с теми же критериями?

**Comment by alexander-rykov** [comment]
@Tounderz да, это два разных процесса, но с одинаковыми критериями одинаковые.
