### ISSUE TITLE
Шаг 14: Реализация Select

### ISSUE THREAD

**Issue by edadasko** [epam-dotnet-lab/file-cabinet-task#46]
Возник вопрос о новой реализации поиска, а именно о команде Select. 
В предыдущих пунктах задания для обоих сервисов были проделаны оптимизации  уже имеющихся команд поиска с помощью добавления словарей. По итогу были созданы 3 словаря для быстрого поиска по полям FirstName, LastName и DateOfBirth, которые оптимизировали поиск до O(1) при запросе, содержащем одно из этих полей. 
В новой команде Select необходимо обеспечить возможность поиска по комбинации различных полей, причем комбинации могут быть двух видов - or и and. Вопрос заключается в следующем: необходимо ли использовать уже имеющиеся словари для оптимизации этого поиска? Сам вижу 2 решения этой проблемы:
1. Отказаться от использования написанных словарей, реализовать поиск комбинации критериев за O(n) + реализовать дополнительную оптимизацию для FileCabinetMemoryService в виде мемоизации в последнем пункте, которая в какой-то мере окупит отсутствие предыдущей оптимизации.
2. Использовать написанные словари в реализации. Вижу следующее решение: дописать словари для каждого из семи полей FileCabinetRecord. Тогда гарантированно каждый запрос может использовать один из словарей для более быстрого поиска. Берется список записей по ключу одного из словаря - в случае And проводится последовательный поиск по списку с целью найти подходящие записи, в случае Or список соединяется со списками из остальных словарей. Возникают следующие нюансы: в случае And - скорость поиска будет существенно зависеть от того, какой из словарей мы выберем первым и будет равняться O(количетсво_записей_в_выбранном_словаре), так как дальнейший поиск выполняется последовательно. В случае Or - неоднозначна скорость соединения результатов из полученных списков, так как в них могут быть повторяющиеся элементы.

Первый подход прост в реализации, поиск за O(n), улучшение в FileCabinetMemoryService за счет мемоизации. Второй подход относительно сложен в реализации, поиск выполняется быстрее (предположительно, хотя в случае And нужно разбираться подробнее), большие затраты памяти для хранения всех словарей.
Естественно, я предполагаю, что существует и более оптимальный способ поиска, чем описанный в пункте 2. Стоит ли искать что-то более оптимальное по времени, или же лучше реализовать что-то попроще, как в пункте 1? Просто довольно трудно самому найти баланс между простотой, скоростью и затратами памяти, поэтому интересуюсь о технических требованиях.

**Comment by alexander-rykov** [comment]
в принципе, любой из вариантов рабочий. 

"Использовать написанные словари в реализации. Вижу следующее решение: дописать словари для каждого из семи полей FileCabinetRecord. Тогда гарантированно каждый запрос может использовать один из словарей для более быстрого поиска." - вот это хороший.

"Второй подход относительно сложен в реализации, поиск выполняется быстрее (предположительно, хотя в случае And нужно разбираться подробнее), большие затраты памяти для хранения всех словарей." - а чего тут сложного? сначала выборка из словарей для каждого из условий, второй этап - совмещение результатов первого при помощи AND или OR.

но и первый вариант устраивает.

**Comment by alexander-rykov** [comment]
"Естественно, я предполагаю, что существует и более оптимальный способ поиска, чем описанный в пункте 2. Стоит ли искать что-то более оптимальное по времени, или же лучше реализовать что-то попроще, как в пункте 1? Просто довольно трудно самому найти баланс между простотой, скоростью и затратами памяти, поэтому интересуюсь о технических требованиях."

полюбопытствуйте, как работают и устроены индексы в RDBMS
https://habr.com/ru/post/102785/
