### ISSUE TITLE
Шаг номер 4: вопрос по предупреждениям компилятора

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/file-cabinet-task#48]
Здравствуйте, Александр! Интересует следующий вопрос.
Уже несколько шагов несу несколько предупреждений компилятора 
1. Warning	CA1062	In externally visible method 'int FileCabinetService.CreateRecord(string firstName, ........)', validate parameter 'firstName' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.	FileCabinetApp.
Проблема в том, что валидацию аргументов я вынес в отдельный метод, в котором СА1062 и появился. Эта же проблема ещё в одним методе того же класса (FileCabinetService).Также ещё в двух методах те же warning'и.  В них проверка происходит перед вызовом из метода класса Program.
Как поступить - убрать валидацию из отдельно метода для первых двух (но тогда будет дублирование кода и метод будет в 1,5 больше), а для следующих двух добавить в них проверку на null, либо не делать с ними ничего?
2. warning CA1822: Member GetRecordsFromDictionary does not access instance data and can be marked as static.
Меняю метод на static и warning всё равно остаётся. В чём может быть проблема? Или не обращать на него внимания?

**Comment by alexander-rykov** [comment]
1. CA1062 - в чем, по вашему мнению, причина предупреждения? Как это связано с валидацией?

**Comment by vysotnikolay** [comment]
Причина в том, что в теле метода нет проверки на null. Проверка всех аргументов вынесена в отдельный метод. Под валидацией я имелл ввиду проверку аргументов.

**Comment by alexander-rykov** [comment]
Верно. Ваш код:

```
public FileCabinetRecord[] FindByFirstName(string firstName)
{
    return this.GetRecordsFromDictionary(firstName, this.firstNameDictionary);
}
```

Вы используете (передаете в метод GetRecordsFromDictionary) переменную firstName, компилятор предупреждает, что без дополнительной проверки возможны проблемы (например, выброс исключения NullReferenceException).

[Документация на правило](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019) гласит:

_Rule description
All reference arguments that are passed to externally visible methods should be checked against null. If appropriate, throw a ArgumentNullException when the argument is null._

Предположим, в метод FindByFirstName передали null. Дальше происходит вызов метода GetRecordsFromDictionary:

```
private FileCabinetRecord[] GetRecordsFromDictionary(string key, Dictionary<string, List<FileCabinetRecord>> dictionary)
{
    List<FileCabinetRecord> valuesList;
    dictionary.TryGetValue(key.ToUpperInvariant(), out valuesList);
    return (valuesList is null) ? Array.Empty<FileCabinetRecord>() : valuesList.ToArray();
}
```

key равен null, при вызове key.ToUpperInvariant() происходит выброс исключения NullReferenceException.

В описании правила есть подсказка, когда подобные предупреждения можно отключить:

_When to suppress warnings
You can suppress a warning from this rule if you are sure that the dereferenced parameter has been validated by another method call in the function._

В вашем случае в методе GetRecordsFromDictionary проверки параметра key на null тоже нет.

Итого:
* В вашем коде при вызове FindByFirstName(null) происходит выброс исключения NullReferenceException в методе GetRecordsFromDictionary, который вызывается из FindByFirstName. Сообразить, почему так произошло без анализа кода методов сложно.
* Если добавить проверку на null в FindByFirstName + throw new ArgumentNullException(nameof(firstName)), то по названию исключения и имени параметра гораздо лечге понять в чем здесь проблема.
* Для CreateRecord предупреждение можно отключить, так как проверка происходит в методе ValidateArguments.

```
[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Justification = "Parameters are checked in ValidateArgumets method.")]
public int CreateRecord(string firstName, string lastName, DateTime dateOfBirth, short zipCode, string city, string street, decimal salary, char gender)
{ }
```

**Comment by alexander-rykov** [comment]
_warning CA1822: Member GetRecordsFromDictionary does not access instance data and can be marked as static.
Меняю метод на static и warning всё равно остаётся. В чём может быть проблема? Или не обращать на него внимания?_

Предупреждение исчезает, если метод сделать статическим.

```
private static FileCabinetRecord[] GetRecordsFromDictionary(string key, Dictionary<string, List<FileCabinetRecord>> dictionary)
{
    List<FileCabinetRecord> valuesList;
    dictionary.TryGetValue(key.ToUpperInvariant(), out valuesList);
    return (valuesList is null) ? Array.Empty<FileCabinetRecord>() : valuesList.ToArray();
}
```

**Comment by vysotnikolay** [comment]
Александр, спасибо за подробнейшее разъяснение.
По поводу метода
private FileCabinetRecord[] GetRecordsFromDictionary(string key, Dictionary<string, List<FileCabinetRecord>> dictionary)
Я думал, что если в вызывающем коде (из класса Program) есть проверки, то в  GetRecordsFromDictionary(string key, Dictionary dictionary) уже необязательно делать проверки, поэтому и возник мой вопрос.
А по поводу модификатора static в этом же методе и других подобных был нюанс, что не сразу и не всегда появлялся, либо исчезал CA1822 warning (то есть анализатор как бы жил своей жизнью в случае с этим warning'ом не зависимо от того, есть модификатор static или нет). Почему - так и не разобрался. В любом случае после добавления static и dotnet build этот warning исчез. Меня интересовало, что может быть вы знаете,в чём может быть причина того, что он так себя ведёт - то появится, то исчезнет, глюк какой-то...
Ещё раз спасибо за исчерпывающий ответ.

**Comment by alexander-rykov** [comment]
_Я думал, что если в вызывающем коде (из класса Program) есть проверки, то в GetRecordsFromDictionary(string key, Dictionary dictionary) уже необязательно делать проверки, поэтому и возник мой вопрос._

вы не можете предсказать, в каком месте будет вызван _GetRecordsFromDictionary_, поэтому проверка все должна быть.

_dotnet build этот warning исчез_

см. флаг [no-incremental](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
