### ISSUE TITLE
Step 4: метод Program.Find.

### ISSUE THREAD

**Issue by dashakunica** [epam-dotnet-lab/file-cabinet-task#49]
Здравствуйте, Александр. В задании написано "Реализуйте новую команду find, которая должна принимать два параметра - имя свойства и искомый текст.". Скажите пожалуйста, тут имеется в виду, что метод Find должен принимать два параметра. Если да, то нужно ли создавать новый массив typle, который в качестве Action принимает два параметра. Или тут имелось в виду, что параметр в методе может быть один, но в самом методе уже разделяется на свойство и искомый текст.

**Comment by alexander-rykov** [comment]
В задании имеется ввиду использование. См. пример.
