### ISSUE TITLE
Шаг 6: Освобождение ресурсов

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#5]
Нужно ли как-то беспокоиться о освобождении StreamWriter, получаемого в аргументах функций?

**Comment by alexander-rykov** [comment]
StreamWriter реализует IDispose, значит владеет каким-то управляемым или неуправляемым ресурсом. Следовательно, объект SW после использования нужно освободить.

Кто это должен сделать? Чтобы ответить на этот вопрос, Вам нужно разобраться кто владеет этим ресурсом. Несколько смущает фраза про "получаемого в аргументах функций", поэтому приведу несерьезную иллюстрацию для примера.

Мальчик Саша хочет поиграть с машинкой, которая стоит на полке. Вы разрешаете ему взять машинку при условии, что Саша вернет ее обратно на полку как только он перестанет играть. Саша немного с машинкой поиграл, а потом передал машинку другому мальчику - Сереже.

Кто теперь должен вернуть машинку обратно на полку? Тот, кто машинкой владеет.

Если игрушкой владеет Сережа, то отнести машинку на полку он должен именно он. Однако, если Сережа вернет машинку на полку, а Саша захочет с ней поиграть, то Саша очень расстроится и заплачет, когда не найдет машинку в комнате (взять машинку с полки он не догадается - он ведь знает, что там ее нет).

Если машинкой владеет Саша, то Сережа после игры должен вернуть машинку обратно Саше, а Саша отнесет игрушку обратно на полку. Если Саша снова захочет поиграть с машинкой, ему снова придется идти к Вам и просить Ваше разрешение.

Обычно следуют практике "ты взял - ты и верни", для упрощения использования которой добавили в язык конструкцию using.

**Comment by alexander-rykov** [comment]
В C# нет дополнительной семантики "владения". Поэтому, можно сделать двойное освобождение ресурсов. Что-то вроде:

var myClass = new MyClass();
foo(myClass);
myClass.Dispose();

foo(MyClass myClass) {
    myClass.Dispose();
}

Иногда такая семантика в языке присутствует - [rust](https://rurust.github.io/rust-by-example-ru/scope/move.html).
