### ISSUE TITLE
Step 6: export to XML

### ISSUE THREAD

**Issue by dashakunica** [epam-dotnet-lab/file-cabinet-task#50]
Скажите пожалуйста, можно ли использовать System.Xml.Linq при создании xml файла?

**Comment by alexander-rykov** [comment]
"Также реализуйте класс FileCabinetRecordXmlWriter, который должен сериализовывать запись в формат XML при помощи XmlWriter."

XmlWriter не входит в пространство имен System.Xml.Linq.
