### ISSUE TITLE
Шаг 7: List в FileCabinetFilesystemService

### ISSUE THREAD

**Issue by dashakunica** [epam-dotnet-lab/file-cabinet-task#51]
Скажите пожалуйста, должны ли мы в FileCabinetFilesystemService добавлять все записи в List альтернативно FileCabinetMemoryService. Возникает вопрос с методами, которые должны возвращать ReadOnlyCollection<FileCabinetRecord>, например GetRecords(). Мы получаемся считываем бинарную запись, а потом кэшируем ее в List для того, чтобы вернуть ReadOnlyCollection, верно? Но вот возникает диссонанс - почему бы нам не добавлять в лист просто при создании записи. Или нам переделать интерфейс IFileCabinetService, чтобы имплементация того же метода GetRecords() выглядела иначе.

**Comment by alexander-rykov** [comment]
_Мы получаемся считываем бинарную запись, а потом кэшируем ее в List для того, чтобы вернуть ReadOnlyCollection, верно?_

1) Вы считываете запись из файла.
2) Превращаете бинарную запись в сущность.
3) Добавляете в List.
4) Возвращаете ReadOnlyCollection, который инкапсулирует List и является оберткой над ним.

Где здесь кэширование?

_Но вот возникает диссонанс - почему бы нам не добавлять в лист просто при создании записи._

Видимо потому, что у вас выходит memory service, а не file service. :)

_Или нам переделать интерфейс IFileCabinetService_

В этом случае интерфейс FileCabinetFilesystemService будет отличаться от FileSystemMemoryService. Смысл задания в том, что у нас общий интерфейс, а реализация отличается.

**Comment by dashakunica** [comment]
Да, я все поняла. Спасибо большое. С кэшированием прочитала - действительно перепутала понятия.
