### ISSUE TITLE
Шаг номер: 3

### ISSUE THREAD

**Issue by ZerSQL** [epam-dotnet-lab/file-cabinet-task#52]
(https://user-images.githubusercontent.com/52918049/76715004-5da44700-673b-11ea-8eb2-d07666b1286d.png)
После первого закрытия приложения появились 2 предупреждения, не понимаю как от них избавиться, подозреваю что появились из-за создания file-cabinet-task.sln файла.

**Comment by alexander-rykov** [comment]
1. у вас вместо сообщения об ошибке псевдографика. попробуйте, изменить настройки windows 10 и включить кириллицу (если у вас англоязычная версия ОС):
https://rpeshkov.net/blog/cyrillic-symbols-on-english-windows/

если не поможет, ищите помощь в гугле.

2. забрал ваш проект, текст ошибки - "Unable to find a project to restore!".

d:\Work\file-cabinet-task (master -> origin)
λ dotnet restore && dotnet build
C:\Program Files\dotnet\sdk\3.1.102\NuGet.targets(123,5): warning : Unable to find a project to restore! [d:\Work\file-cabinet-task\FileCabinet.sln]
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.1.102\NuGet.targets(123,5): warning : Unable to find a project to restore! [d:\Work\file-cabinet-task\FileCabinet.sln]

Build succeeded.

C:\Program Files\dotnet\sdk\3.1.102\NuGet.targets(123,5): warning : Unable to find a project to restore! [d:\Work\file-cabinet-task\FileCabinet.sln]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.25

3. посмотрел в ваш [FileCabinet.sln](https://github.com/ZerSQL/file-cabinet-task/blob/master/FileCabinet.sln) - там нет добавленных csproj файлов. т.е. ваша ошибка в том, что вы забыли добавить проект в solution.
