### ISSUE TITLE
Шаг 5,8 и тд: параметры командной строки (доп пакеты).

### ISSUE THREAD

**Issue by dashakunica** [epam-dotnet-lab/file-cabinet-task#53]
После прохождения темы конфигурации на треннинге возник вопрос. Можно ли использовать для парсинга командной строки пакет Microsoft.Extensions.Configuration.CommandLine.dll. Нигде не оговорено, что его можно добавить, но в степах дальше идет конфигурация и этот пакет хорошо ложиться для обработки командной строки, поэтому решила уточнить. Спасибо.

**Comment by alexander-rykov** [comment]
Да, действительно, этот пакет использовать удобно для обработки командной строки.
Нет, использовать в вашем приложении нельзя.
