### ISSUE TITLE
Шаг 7: Уточнение по поводу полей и принципу хранения в файле cabinet-records.db

### ISSUE THREAD

**Issue by anischenkozhenya** [epam-dotnet-lab/file-cabinet-task#54]
1)
![image](https://user-images.githubusercontent.com/43790223/79688512-6f579d80-8257-11ea-8d4f-593ce82a7c7f.png) поле Status это пользовательское поле которое надо было придумать самому или что именно оно должно хранить?
2)cabinet-records.db при каждом запуске программы дописываем в конец или обнуляем документ и пишем с нуля?
3)При запуске мы создаем FileStream пока не завершим процесс? или при каждой команде открываем выполняем действие и закрываем. Файл хранит данные пока программа не запущена, а FileStream при запуске загружает в себя данные, пока не закроем приложение?

**Comment by alexander-rykov** [comment]
1. Reserved - пока не используется.
2. Добавление данных - да, пишем в конец при новом запуске.
3. Стрим открыт пока идет работа с сервисом. 
4. "Файл хранит данные пока программа не запущена, а FileStream при запуске загружает в себя данные, пока не закроем приложение?" - нет, файловый сервис постоянно работает с файлом.
