### ISSUE TITLE
Шаг 6: как получить название файла из xmlwriter?

### ISSUE THREAD

**Issue by Stanlox** [epam-dotnet-lab/file-cabinet-task#55]
Есть ли какой способ получить название файла из xmlWriter для создания настроек (XmlWriter.Create()). Первым параметром передаётся путь, но как его вытащить из xmlWriter. Если этого не сделать то в результате в xml запишутся лишние данные и в неверном форматировании.

**Comment by alexander-rykov** [comment]
Непонятно, зачем это вам нужно. Какие лишние данные, почему в неверном форматировании? Приведите пример кода.

**Comment by Stanlox** [comment]
В итоге сериализации в файле появляются не понятные ссылки, да и все данные записаны в одну строчку. Я хотел через settings указать формат выходных данных! 
>Понедельник, 4 мая 2020, 17:57 +03:00 от Aliaksandr Rykau <notifications@github.com>:
> 
> 
>Непонятно, зачем это вам нужно. Какие лишние данные, почему в неверном форматировании? Приведите пример кода.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Максим Бондарук

**Comment by alexander-rykov** [comment]
> В итоге сериализации в файле появляются не понятные ссылки, да и все данные записаны в одну строчку. Я хотел через settings указать формат выходных данных!
> Понедельник, 4 мая 2020, 17:57 +03:00 от Aliaksandr Rykau ***@***.***>:     Непонятно, зачем это вам нужно. Какие лишние данные, почему в неверном форматировании? Приведите пример кода. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .
>     -- Максим Бондарук

приведите пример выходного файла.

**Comment by Stanlox** [comment]
>Понедельник, 4 мая 2020, 19:25 +03:00 от Aliaksandr Rykau <notifications@github.com>:
> 
> 
>В итоге сериализации в файле появляются не понятные ссылки, да и все данные записаны в одну строчку. Я хотел через settings указать формат выходных данных!
>Понедельник, 4 мая 2020, 17:57 +03:00 от Aliaksandr Rykau  @ .***>:     Непонятно, зачем это вам нужно. Какие лишние данные, почему в неверном форматировании? Приведите пример кода. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .
>    -- Максим Бондарук
приведите пример выходного файла.
—
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .  
 
--
Максим Бондарук

**Comment by alexander-rykov** [comment]
@Stanlox здесь должно что-то быть? я не вижу ни примера кода, ни примера выходного файла.
