### ISSUE TITLE
Шаг 8:импорт из csv и xml

### ISSUE THREAD

**Issue by ZerSQL** [epam-dotnet-lab/file-cabinet-task#56]
![вывод консоли](https://user-images.githubusercontent.com/52918049/81319041-c521a780-9097-11ea-9890-a4100244db87.jpg)
![предупреждения](https://user-images.githubusercontent.com/52918049/81319050-c81c9800-9097-11ea-9448-4e59a9d2ff6b.JPG)
На шаге 8 возникло несколько вопросов:
1. При случайной генерации данных FileCabinetGenerator мы должны использовать получение случайной строки (как на скриншоте) либо создание 2х заранее предусмотренных массивов строк firstname и lastname и взятия случайного имени и фамилии из них?
2. После создания FileCabinetGenerator компилятор начал выдавать предупреждения SA1200, SA1633, и CA1303, хотя code-analysis.ruleset не изменялся, да и при его просмотре видно, что на них стоят действия "None".

**Comment by ZerSQL** [comment]
И небольшая поправка: терминал при сборке предупреждения не выдаёт.

**Comment by alexander-rykov** [comment]
1. При генерации данных допустимо:
a) полностью случайные строки
б) "массивы с данными в программе"
б) можно использовать внешние библиотеки
https://github.com/bchavez/Bogus
https://github.com/oriches/faker-cs

**Comment by alexander-rykov** [comment]
2. code-analysis.ruleset расположен в каталоге проекта FileCabinet, его действие не распространяется на FileCabinetGenerator.

Можно:
a) Скопировать файл code-analysis.ruleset в каталог проекта генератора.
б) Перенести code-analysis.ruleset в каталог с .sln, и изменить в файлах проекта .csproj путь к файлу:
`<CodeAnalysisRuleSet>../code-analysis.ruleset</CodeAnalysisRuleSet>
`
Если не поможет, то залейте код ветки в гитхаб и напишите мне, я посмотрю.

**Comment by ZerSQL** [comment]
Помогло пересоздание файла code-analysis в том же каталоге и указание пути к нему вручную в файле csproj. Спасибо.
