### ISSUE TITLE
Шаг 7: Проблемы с передачей параметров в main

### ISSUE THREAD

**Issue by Stanlox** [epam-dotnet-lab/file-cabinet-task#57]
При передаче параметров в метод main с помощью консоли(git bash, powershell) выкидывает exception "Index was ourside bounds of the array ", но при передаче параметров через свойство проекта всё работает отлично. Это может быть как-то связано с тем что для получение exe файл я использовал dotnet-publish -r win-64?

**Comment by alexander-rykov** [comment]
@Stanlox приведите текст исключения, которое вы видите в консоли

**Comment by Stanlox** [comment]
![image](https://user-images.githubusercontent.com/51272551/81562832-27cbb980-939e-11ea-95a6-53d9f9c1f02d.png)

**Comment by alexander-rykov** [comment]
Видимо, Ваши изменения еще не залиты на гитхаб:

        public static void Main() // no parameters - String[] args
        {
            Console.Write("Validations rules: ");
            var validationsRules = Console.ReadLine().Trim(' ').Split(new char[] { ' ', '=' }, StringSplitOptions.RemoveEmptyEntries);
            **var longDescription = "--validation-rules"; // line 57**
            var shortDescription = "-v";

https://github.com/Stanlox/EpamStudLab/blob/eadcbe680e80b4dfe877cea161d2f256136a7f7f/FileCabinetApp/Program.cs#L57

Проанализируйте-продебажьте код.

**Comment by alexander-rykov** [comment]
@Stanlox какой результат?

**Comment by Stanlox** [comment]
Не кидает exception если передавать параметры через свойство проекта. Через консоль всё та же проблема.

**Comment by alexander-rykov** [comment]
приведите текст из консоли - команду вызова приложения со всеми аргументами и все, что пишет приложение, включая текст исключения.

**Comment by Stanlox** [comment]
![image](https://user-images.githubusercontent.com/51272551/82340894-6db8fb00-99f8-11ea-9292-8019e8c49c9a.png)

**Comment by alexander-rykov** [comment]
@Stanlox запустил ваш код из ветки "step7-add-filesystem" - все работает.

![image](https://user-images.githubusercontent.com/19323417/82370405-298e2080-9a21-11ea-967a-c25132296f9b.png)

залейте все ваши изменения на гитхаб.

**Comment by Stanlox** [comment]
Разобрался. Необходимо было сгенерировать новый exe файл.
