### ISSUE TITLE
Шаг 7: обработка параметров командной строки

### ISSUE THREAD

**Issue by miseinen** [epam-dotnet-lab/file-cabinet-task#58]
На шаге 7 у нас к правилам валидации добавляются еще параметры коммандной строки для указания места хранения данных,  возникает вопрос их корректной обработки. Можно ли использовать в этих целях библиотеку Command Line Parser (https://github.com/commandlineparser/commandline)?

**Comment by alexander-rykov** [comment]
Нет. Смысл задания в том, чтобы студенты научились работать со строками :)

На подобный вопрос я уже отвечал - https://github.com/epam-dotnet-lab/file-cabinet-task/issues/53.
