### ISSUE TITLE
Шаг 13: Реализация insert

### ISSUE THREAD

**Issue by anischenkozhenya** [epam-dotnet-lab/file-cabinet-task#59]
Как должна работать команда insert, если в списке уже есть запись с тем же id? Переписывать данные как это делает Edit? 
Приветствуется ли использование REGEX?

**Comment by alexander-rykov** [comment]
@anischenkozhenya

insert (id, ...)
1) если id уже существуте, то - ошибка
2) если id не существует, то добавить

есть еще вариант insert без id - inser (...)
