### ISSUE TITLE
Шаг 4: Dictionary

### ISSUE THREAD

**Issue by Mmorski** [epam-dotnet-lab/file-cabinet-task#6]
Объясните пожалуйста смысл добавления словаря. Почему в качестве значений будут коллекции List, а не отдельные записи ? Или же в качестве значений у всех ключей будет одна и та же ссылка на общий List ? Прошу прояснить момент.

**Comment by alexander-rykov** [comment]
1) Выполните задание, затем сравните поведение методов поиска до и после добавления словаря. Сравните, как изменилась сложность поиска.

2) [Индексы](https://ru.wikipedia.org/wiki/Индекс_(базы_данных)):

_Таблицы в базе данных могут иметь большое количество строк, которые хранятся в произвольном порядке, и их поиск по заданному критерию путём последовательного просмотра таблицы строка за строкой может занимать много времени. Индекс формируется из значений одного или нескольких столбцов таблицы и указателей на соответствующие строки таблицы и, таким образом, позволяет искать строки, удовлетворяющие критерию поиска_

3) Попробуйте нарисовать граф ссылок объектов внутри сервиса - как объекты ссылаются друг на друга.

**Comment by alexander-rykov** [comment]
1) Сделали сравнение? Какой результат?
3) Покажите Ваш граф объектов.

**Comment by Mmorski** [comment]
> 1. Сделали сравнение? Какой результат?
> 2. Покажите Ваш граф объектов.

Сделал. Конечно на словарях гораздо быстрее. Если я правильно понял идею, то граф будет такой:
![Untitled](https://user-images.githubusercontent.com/37119881/66770917-77f2a400-eec1-11e9-858c-e886a4fbe0e4.png)

**Comment by alexander-rykov** [comment]
@Mmorski да, верно, граф будет таким. значит, вопрос решен :)
