### ISSUE TITLE
Шаг 10: Применение  Builder Fluent Interface.

### ISSUE THREAD

**Issue by Stanlox** [epam-dotnet-lab/file-cabinet-task#61]
После применение Builder Fluent Interface у нас получился класс ValidatorBuilder, вместо DefaultValidator и CustomValidator.
Не совсем понятно что мы должны теперь передавать в конструктор сервиса, так как раньше мы указывали тип валидатора.
IFileCabinetService service = new FileCabinetMemoryService(new DefaultValidator()).

**Comment by alexander-rykov** [comment]
1) Конструктор вашего сервиса принимает IRecordValidator:

``
public FileCabinetMemoryService(IRecordValidator strategy)
``

Поэтому код в Вашем вопросе можно переписать как

``
IRecordValidator recordValidator = new DefaultValidator();
IFileCabinetService service = new FileCabinetMemoryService(recordValidator).
``

2) Класс DefaultValidator реализует IRecordValidator, поэтому Вы передавали объект класса в сервис.

3) Метод ValidatorBuilder.Create() возвращает объект типа IRecordValidator. Вот пример использования из 10го шага:

``
IRecordValidator recordValidator = new ValidatorBuilder()
    .ValidateFirstName(min, max)
    .ValidateLastName(min, max)
    .ValidateDateOfBirth(from, to)
    .Create();
``

Этот объект и нужно передать в Ваш сервис:
