### ISSUE TITLE
Шаг 12: Поиск записей в файле

### ISSUE THREAD

**Issue by Stanlox** [epam-dotnet-lab/file-cabinet-task#62]
"Добавьте в класс FileCabinetFilesystemService индексы по полям, где ключем будет искомое поле, а значением - список смещений записей от начала файла". Что здесь подразумевается под индексом для поля, список смещений записей от начало файла? Окончательный вид словаря для поиска должен иметь вид:
Пример : DictionaryList<string, SortedDictionary<List<FileCabinetRecord>, int>>?

**Comment by alexander-rykov** [comment]
1) DictionaryList - такого типа вроде нет в BCL.

2) Как Вы видите использование этой структуры? что будет аргументами метода:

this.dictionary.Add(?, ?)

**Comment by Stanlox** [comment]
1. Да, перепутал, имел ввиду обычный словарь.
2. Видимо Dictionary<string, List<int>>?

**Comment by alexander-rykov** [comment]
2.1. если индексируемое поле - строка, то первый тип будет string. если не строка, то соответствующий тип.
2.2. второй параметр - List<< long >> или List<< int >>, смещение в файле.
