### ISSUE TITLE
Шаг 3: Описание команд  

### ISSUE THREAD

**Issue by MenLanda** [epam-dotnet-lab/file-cabinet-task#63]
Каждый вложенный массив helpMessages содержит 3 элемента:
1 - название команды,
2 - краткое описание,
3 - подробное описание.
Как должно работать подробное описание команды, при вводе каких значений программа их выдаёт?

**Comment by alexander-rykov** [comment]
1) Как должно работать подробное описание команды

Подробное описание команды выводится на экран, если пользователь вводит имя команды после команды help. Пример:

```sh
> help help
The 'help' command prints the help screen.
> help exit
The 'exit' command exits the application.
``` 

См. метод PrintHelp.

2) при вводе каких значений программа их выдаёт?

"их" - это что?
