### ISSUE TITLE
Шаг 9: purge 

### ISSUE THREAD

**Issue by anatoli-hancharou** [epam-dotnet-lab/file-cabinet-task#65]
Как и с методом MakeSnapshot, для добавления метода Purge нужно добавить его в интерфейс IFileCabinetService, соответственно оба класса: FileCabinetMemoryService и FileCabinetFilesystemService должны этот метод реализовать. Но поскольку в классе FileCabinetMemoryService он использоваться не будет, то вместо реализации он будет бросать NotImplementedException как заглушку. Это верное решение, или я что-то упускаю?

**Comment by alexander-rykov** [comment]
@anatoli-hancharou извините, не заметил вопрос. он еще актуален?

**Comment by anatoli-hancharou** [comment]
Скорее остался вопрос по поводу MakeSnapshot. Или я не заметил, или его нигде не требуется реализовывать для FileCabinetFilesystemService.

**Comment by alexander-rykov** [comment]
@anatoli-hancharou изначально MakeSnapshot реализуется для FileCabinetService. Соответственно, эта функциональность должна перейти в FileCabinetFilesystemService.
