### ISSUE TITLE
Шаг 5: Валидаторы ввода

### ISSUE THREAD

**Issue by madopew** [epam-dotnet-lab/file-cabinet-task#66]
Почитав #3 вопрос с валидацией пользовательского ввода все еще остался открытым.

Я правильно понимаю, что не нужно пытаться динамически доставать правила валидации из сервиса (например мин. и макс. длину строки) или выделять отдельные для этого методы, а просто написать те же проверки в классе Program?

То есть, вместо этого
```c#
bool FirstNameValidator (string firstName)
{
    return firstName.Length > FileCabinetCustomService.MinFirstNameLength;
}
```
Использовать это
```c#
private readonly int MinFirstNameLength;
void Main (string[] args)
{
    MinFirstNameLength = 2; // в зависимости от validation-rules задавать эти readonly значения
    ...
}

bool FirstNameValidator (string firstName)
{
    return firstName.Length > this.MinFirstNameLength;
}
```

**Comment by alexander-rykov** [comment]
в шаге 5 вы должны создать классы для валидации данных, которые должен инкапсулировать (=объединять) параметры валидации и методы валидации (DefaultValidator и CustomValidator)

https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/images/step05-template-method-with-strategy.png

_"Я правильно понимаю, что не нужно пытаться динамически доставать правила валидации из сервиса (например мин. и макс. длину строки)"_

правильно.

_"или выделять отдельные для этого методы"_

нужно выделить объект.

_"а просто написать те же проверки в классе Program?"_

проверки будут выглядеть немного иначе. см. "Рефакторинг кода валидации данных"
https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/step05.md#%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D0%BA%D0%BE%D0%B4%D0%B0-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85
