### ISSUE TITLE
Шаг 9: пометка о удаленной записи

### ISSUE THREAD

**Issue by ArtemiyGalkov** [epam-dotnet-lab/file-cabinet-task#67]
Должны ли эти 16 бит (2 зарезервированных, 1 IsDeleted и еще 13 зарезервированных) быть записаны в файле рядом с соответствующими им записями? Если да, то имеет ли значение их расположение относительно основной информации о записи (до или после нее), и имеет ли в таком случае смысл оставлять 2 зарезервированных бита из начала основной записи?

**Comment by alexander-rykov** [comment]
извините, не сразу заметил

_Должны ли эти 16 бит (2 зарезервированных, 1 IsDeleted и еще 13 зарезервированных) быть записаны в файле рядом с соответствующими им записями?_

да.

_Если да, то имеет ли значение их расположение относительно основной информации о записи (до или после нее),_

эти биты являются частью записи. формат был одинаковым для всех записей. но, хотите пишите до остальных полей, хотите - после.

_и имеет ли в таком случае смысл оставлять 2 зарезервированных бита из начала основной записи?"_

не понял, что такое "основная запись".
