### ISSUE TITLE
Шаг 6: Export to Xml передаваемый параметр StreamWriter

### ISSUE THREAD

**Issue by egterent** [epam-dotnet-lab/file-cabinet-task#69]
Здравствуйте.
В метод FileCabinetServiceSnapshot.SaveToXml передается StreamWriter, может быть здесь должен быть Stream, который можно передать в XmlWriter.Create, или экземпляр XmlWriter?

**Comment by alexander-rykov** [comment]
нет, не stream, а streamwriter
