### ISSUE TITLE
Шаг 7: Пункты 4 и 5 полностью идентичны(исключая названия функций, которые нужно релизовать)

### ISSUE THREAD

**Issue by ffje** [epam-dotnet-lab/file-cabinet-task#7]

**Comment by alexander-rykov** [comment]
Верно, это ошибка. Я сделал изменение. Подумайте, как лучше сформулировать этот пункт.

**Comment by alexander-rykov** [comment]
@ffje к сожалению, не получит от вас примера, как можно сделать этот пункт лучше.

**Comment by ffje** [comment]
я бы предложил вариант пункта 5:  "Реализуйте метод FileCabinetFileService.GetStat, который должен возвращать количество записей, сохраненных в файле. Метод должен руководствоваться размером файла, а не устанавливать указатель на начало файла (BOF) и последовательно анализировать записи, считая их количество."

**Comment by alexander-rykov** [comment]
@ffje вы уже подсказываете реализацию метода, а это не совсем корректно :) к тому же, сервис может хранить количество записи во внутреннем поле, а не вычислять это значение каждый раз (последовательно читая записи или по размеру файла).

спасибо, вставил первое предложение.
