### ISSUE TITLE
Шаг 10: Валидация ввода после рефакторинга

### ISSUE THREAD

**Issue by nmaliukov** [epam-dotnet-lab/file-cabinet-task#71]
Вы сказали, что валидации и валидации это две разные вещи, что это значит?
Как можно получить те самые "общие правила" для провдения валидации ввода данных из шага 5, если они инкапсулированы в ValidatorBuilder и даже после получения одного из валидаторов, правила всё равно будут инкапсулированы внутри классов выполняющих проверку той самой валидации. Т.е создать иную проверку на основе уже имеющихся правил к которым мы не можем получить доступ - вводит меня в ступор. В чём я ошибаюсь?

**Comment by alexander-rykov** [comment]
IRecordValidator - это интерфейс объектов, которые валидируют запись при добавлении в сервис. ValidatorBuilder создает и настраивает объекты таким образом, чтобы вы получили настроенный валидатор.

Классы валидации записей не имеют отношения к валидации данных при вводе. Не нужно использовать IRecordValidator для валидации данных при вводе.

**Comment by nmaliukov** [comment]
Хорошо, тогда по каким правилам нужно проводить валидацию ввода?

**Comment by alexander-rykov** [comment]
правила - аналогичные сервисным, код может быть другим

**Comment by nmaliukov** [comment]
Должны ли динамически меняться правила при изменении их в Duefault либо Custom версии при добавлении в сервис или они абсолютно независимы?

**Comment by nmaliukov** [comment]
Всё, всё-таки додумался)
Невнимательно прочитал ваше сообщение, всё безумно просто.
