### ISSUE TITLE
Шаг 5: Можно ли изменить класс на абстрактный?

### ISSUE THREAD

**Issue by Dizment** [epam-dotnet-lab/file-cabinet-task#72]
Можно ли изменить класс FileCabinetService на абстрактный класс, чтобы применить шаблонный метод и написать два класса на проверку критериев?

**Comment by alexander-rykov** [comment]
Не понял вопрос. В тексте пункта (5) сказано:

_"FileCabinetService можно с помощью шаблона проектирования - Template Method. Реализуйте этот шаблон, как показано на диаграмме классов."_

Диаграмма классов: https://github.com/epam-dotnet-lab/file-cabinet-task/blob/master/images/step05-template-method.png

Далее см. сюда: https://refactoring.guru/ru/design-patterns/template-method

Раздел структура:

_"Абстрактный класс определяет шаги алгоритма и содержит шаблонный метод, состоящий из вызовов этих шагов. Шаги могут быть как абстрактными, так и содержать реализацию по умолчанию."_

Рисунок:
https://refactoring.guru/images/patterns/diagrams/template-method/structure.png?id=924692f994bff6578d84

Вопросы к вам:

1) "Является ли абстрактным класс AbstractClass, который изображен на рисунке выше?"
2) "Является ли абстрактным класс, который изображен на диаграмме выше?"

**Comment by Dizment** [comment]
Да, являются. Спасибо за ответ.
