### ISSUE TITLE
Шаг 4 - Поиск.

### ISSUE THREAD

**Issue by MikAleinik** [epam-dotnet-lab/file-cabinet-task#73]
Добрый день.
Возникло затруднение в п.4 - _В класс FileCabinetService добавьте поле-словарь, которое должно работать как индекс полю FirstName._ 
В словарь _Dictionary<string, List< FileCabinetRecord > >_ при добавлении элемента из _List< FileCabinetRecord >_  попадает объект, а не ссылка на объект. Что, как я понимаю, удваивает использование памяти. 
И при удалении объекта из _List< FileCabinetRecord >_ он остается в словаре. Как я понимаю "задвоение" данных и в _List_ и в _Dictionary_ не есть хорошо и в _Dictionary_ должна попадать ссылка на включенный в _List_ объект. 
Но как ни пробовал это реализовать, не выходит - прошу подсказать в какую сторону копать, где почитать.

**Comment by alexander-rykov** [comment]
1) _при добавлении элемента из List< FileCabinetRecord > попадает объект, а не ссылка на объект. Что, как я понимаю, удваивает использование памяти._

почему объект, а не ссылка на объект?

2) _И при удалении объекта из List< FileCabinetRecord > он остается в словаре._

когда объект удаляется из List?

**Comment by MikAleinik** [comment]
> почему объект, а не ссылка на объект?

Сам себя запутал и вас зря потревожил. Но в чтении документации просветил для себя темные пятна.
И _List_ и _Dictionary_ ссылаются на один и тот же объект. Ни какого задвоения памяти нет. :)
Один только вопрос есть. В топике [https://github.com/epam-dotnet-lab/file-cabinet-task/issues/6](url) показан граф объектов. Если я правильно понимаю нарисованный граф объектов, то в _Dictionary_ содержится ссылка на _List_ в котором содержится ссылка на объект в памяти.
Но _List_ и _Dictionary_ ссылаются на объект не зависимо друг от друга - если я удаляю его из _List_ , то в _Dictionary_ он не теряется. Как я понимаю граф ссылок выглядит так?
![1](https://user-images.githubusercontent.com/84644126/120105115-3ed37a00-c160-11eb-8cbb-2d5a2da18c37.jpg)

> когда объект удаляется из List?

Объект подлежит удалению из памяти тогда, когда на него не остается ссылок.

**Comment by alexander-rykov** [comment]
_Но List и Dictionary ссылаются на объект не зависимо друг от друга - если я удаляю его из List , то в Dictionary он не теряется._ - верно.

_Как я понимаю граф ссылок выглядит так?_ - в List<Person> и в Value List<Person> (в словаре) содержатся ссылки на объекты. если у вас изображены ссылки, то верно.

**Comment by MikAleinik** [comment]
> _Как я понимаю граф ссылок выглядит так?_ - в List и в Value List (в словаре) содержатся ссылки на объекты. если у вас изображены ссылки, то верно.

Изображены ссылки. Только все равно не понимаю почему граф объектов отличается. 
Спасибо.

**Comment by alexander-rykov** [comment]
в #6 не совсем корректно изобрашен список list - объекты словно содержатся в списке. это не так. список из словаря указывает на объект и list тоже должен указывать на объект.

**Comment by MikAleinik** [comment]
Понял. Спасибо за помощь.
