### ISSUE TITLE
Шаг 5: Добавление параметра командной строки приложения

### ISSUE THREAD

**Issue by mstruhalski** [epam-dotnet-lab/file-cabinet-task#77]
Здравствуйте. Столкнулся с проблемой при добавлении параметра командной строки приложения. Совсем не понимаю, как это надо делать. Можете, пожалуйста, натолкнуть на мысль, или подсказать, где можно про это почитать?

**Comment by grysbok** [comment]
1. Можно вызывать приложение с указанием параметров коммандной строки через cmd.exe.
2. Можно задать параметры для старта приложения из VS - https://stackoverflow.com/questions/6475887/passing-command-line-parameters-with-visual-studio-c-sharp

**Comment by mstruhalski** [comment]
Можете, пожалуйста, подробнее описать пункт 1? Не совсем понимаю, о чём идёт речь.
Пункт 2 реализовать не получается, потому что пишу в Rider, там такой функции найти не могу.

**Comment by alexander-rykov** [comment]
1. "program.exe Argument1 Argument2 Argument3"
2. https://www.jetbrains.com/help/rider/Get_Started_with_Run_Debug_Configurations.html#step-1-understand-run-debug-configurations

**Comment by mstruhalski** [comment]
Спасибо! Буду разбираться.
