### ISSUE TITLE
Шаг 1: (не?) применение анализатора FxCopAnalyzers

### ISSUE THREAD

**Issue by vacho87** [epam-dotnet-lab/file-cabinet-task#78]
В пункте 6 Шага 1 указано, что необходимо установить в проект анализатор кода Microsoft.CodeAnalysis.FxCopAnalyzers.
При этом Visual Studio выдает Warning CA9998:
<img width="702" alt="Снимок1" src="https://user-images.githubusercontent.com/70841961/131169382-c3f076a1-1275-4270-be3e-e92e5a252650.PNG">
Из описания предупреждения следует, что данный анализатор устарел и требует замены более современными аналогами. 
Как в данном случае следует поступать: подавить warning, удалить данный анализатор или заменить предлагаемыми альтернативами, например nuget package "Microsoft.CodeAnalysis.NetAnalyzers"?

**Comment by alexander-rykov** [comment]
вы используете .NET 5. для этой версии есть свой встроенный анализатор.
1) можно перейти на 3.1, для которой и было написано руководство.
2) использовать новые анализаторы. https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019

**Comment by vacho87** [comment]
Спасибо
