### ISSUE TITLE
Шаг 3: Архитектура реализации валидации данных

### ISSUE THREAD

**Issue by vacho87** [epam-dotnet-lab/file-cabinet-task#79]
В шаге 3 требуется организовать проверку одних и тех же данных в двух местах программы. Правильно ли это с точки зрения архитектуры? 
- Метод FileCabinetService.CreateRecord, в котором должна выполняться проверка валидности данных и, при необходимости, выброс исключений, вызывается методом Program.Create, в котором также должна осуществляться аналогичная проверка этих же данных. То есть, мы на вход в FileCabinetService.CreateRecord получаем от метода Program.Create заведомо валидные параметры (если условия обоих проверок идентичны). В таком случае проверка в FileCabinetService.CreateRecord по сути представляет собой повторное выполнение одно и того же кода, при этом выброса исключений никогда не будет => бесполезная трата машинных ресурсов.
- Возможно по замыслу задания предполагается собственно реализация валидации только в методе FileCabinetService.CreateRecord, а метод Program.Create просто ловит исключения от FileCabinetService.CreateRecord и запрашивает повторный ввод данных пользователем. Но при таком подходе пользователю при некорректном вводе одного из параметров записи потребуется после выброса исключения FileCabinetService.CreateRecord в метод Program.Create полностью повторять ввод всех параметров записи. Либо же для избежания полного повторного ввода нужно в Program.Create делать сложный алгоритм,  при котором введенные пользователем передаются в CreateRecord а из него выбрасывается исключение с признаком свойства, в которое были переданы невалидные данные , запрашивать повторный ввод параметров только для этого свойства, после вновь отправлять все параметры (один - повторно введенный, остальные из предыдущей сессии ввода данных), после чего повторная валидация, и возможно еще один (или более) подобный цикл, так как уведомить вызывающий метод о невалидных данных путем выброса исключения можно будет только по поводу одного невалидного параметра за один вызов.
- Мне более правильным видится проверка данных только на этапе ввода в методе Program.Create (или в вызываемых им методах) до вызова FileCabinetService.CreateRecord.
- Или же есть (предполагались) другие решения?

**Comment by alexander-rykov** [comment]
см. #3.
