### ISSUE TITLE
Шаг 7: Перевод в бинарный вид.

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#8]
Как правильно (более красиво) сериализовывать данные в бинарный вид? Нужно ли для этих целей создавать отдельную структуру данных? Пробовал через unsafe код, не получилось. 
Или же все делается переводом каждого поля в набор byte[] с дальнейшей их помещение в List<byte>() и дальнейшем вызовом ToArray(). Интересует именно альтернативный вариант.

**Comment by vitalmizevich** [comment]
Плюк возникает вопрос с decimal. Как переводить его в byte[]. Создавать struct с двумя long и decimal, шаря общее пространство или есть альтернатива?

**Comment by alexander-rykov** [comment]
1) Для записи-чтения бинарных данных есть [BinaryReader](https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader) и [BinaryWriter](https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter). Они работают со стримом и пишут основные типы.

2) Со строками сложнее. Вариант (1) - писать данные в однобайтовой кодировке, тогда 1 byte = 1 char, но можно легко потерять unicode-символ. Вариант (2) - писать UTF-8, но тогда символ может занимать от 1-го до 4-х байт. Т.о. нужно аккуратно вычислять длину закодированной строки, чтобы уместиться в фиксированный размер. Вариант (3) - UTF-16, если писать латиницу-кириллицу и не баловаться иероглифами, то символы будут размером 2 байта. Для конвертации строк вам пригодится [Encoding](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding).

3) "Плюк возникает вопрос с decimal. Как переводить его в byte[]. " - BinaryWriter умеет и decimal.

4) Также вам может помочь [MemoryStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream).

5) Пример чтения-записи - https://gist.github.com/alexander-rykov/e9af9e09ab0ace109fcc6a6cc98473ae
