### ISSUE TITLE
Шаг номер 6-7: метод MakeSnapshot и методы в интерфейсе.

### ISSUE THREAD

**Issue by Lera919** [epam-dotnet-lab/file-cabinet-task#80]
В шаге 6 создавался метод MakeSnapshot который обращался к нестатическому полю класса list, так что сам метод нельзя сделать статическим, а следовательно нужно обращаться через объект класса. В пункте 5 было сказано: "Используйте этот интерфейс в классе Program в качестве типа поля сервиса." Из этого исходит, что обращаться можно только к функциям, определенным в интерфейсе. В 7 пункте метода MakeSnapshot нет в интерфейсе, сделать его статическим нельзя, тогда как к нему можно обратиться?

**Comment by alexander-rykov** [comment]
можете добавить MakeSnapshot в интерфейс, видимо потерялся
