### ISSUE TITLE
Шаг номер 7: использование словарей

### ISSUE THREAD

**Issue by Lera919** [epam-dotnet-lab/file-cabinet-task#81]
Для FileCabinetRecordFilesystem необходимо реализовать методы с поиском в словаре. Но при запуске программы "по новой" словари пусты, даже при наличии записей в файле. Тогда получается словари так же необходимо записывать в отдельные файлы или заполнять их в конструкторе, основываясь на записи record-ов?

**Comment by alexander-rykov** [comment]
заполнять при загрузке приложения, основываясь на записях в файле.
