### ISSUE TITLE
Шаг 5: ошибка при вызове функции ReadInput

### ISSUE THREAD

**Issue by Gymbotan** [epam-dotnet-lab/file-cabinet-task#82]
Здравствуйте. Не знаю, насколько можно вставлять код из самой программы, поэтому сделал отдельный проект и сильно упростил функции, но ошибка появляется та же:
![1](https://user-images.githubusercontent.com/55342311/134934339-7f1936b5-5bb5-4c08-b383-d8b0f437eaaa.jpg)
Якобы функция возвращает неправильный тип, но все вроде бы соответствует объявлению.
Если вместо кортежа использовать обычный тип, то ошибок нет:
![2](https://user-images.githubusercontent.com/55342311/134934821-f4bfa586-dd04-45b9-9692-def0c4d6afd0.jpg)

Может я как-то не так с кортежами работаю? Или в чем еще может быть проблема?
Заранее спасибо

**Comment by alexander-rykov** [comment]
вы спутали разные типы кортежей, Tuple != ValueTuple.

public static string InputMethod(Func<string, **ValueTuple**<bool, string, string>> converter) { ... }

**Comment by Gymbotan** [comment]
Спасибо. Буду разбираться
27.09.2021, 18:54, Aliaksandr Rykau < ***@***.*** ***@***.*** >
вы спутали разные типы кортежей, Tuple != ValueTuple.
public static string InputMethod(Func<string, ValueTuple <bool, string, string>> converter) { ... }
