### ISSUE TITLE
Шаг 11: журналирование работы сервиса

### ISSUE THREAD

**Issue by anonimCitizen** [epam-dotnet-lab/file-cabinet-task#83]
Текстовый файл должен создаваться каждый раз при запуске приложения/дозаписываться/перезаписываться?

**Comment by alexander-rykov** [comment]
перезаписываться. смысл с том, чтобы хранить журнал работы сервиса за длительный период времени (относительно времени работы сервиса).

**Comment by anonimCitizen** [comment]
спасибо
