### ISSUE TITLE
Шаг 8: проблема с совпадением форматов xml-файлов

### ISSUE THREAD

**Issue by Gymbotan** [epam-dotnet-lab/file-cabinet-task#84]
Здравствуйте. Столкнулся с такой проблемой.
На предыдущих шагах реализовал экспорт, требовался xml следующего вида:
![изображение](https://user-images.githubusercontent.com/55342311/136180788-f9b03ca2-aab4-4f38-8ee7-fea0845e163a.png)

На этом шагу надо использовать сериализацию. Прочитав одну из имеющихся issue, создал новый класс, в котором структура совпадает с требуемой и методы конвертации в FileCabinetRecord и обратно. При сериализации массива или List'а новых объектов получается следующий xml:
![изображение](https://user-images.githubusercontent.com/55342311/136181635-0eda75d3-c99f-49fa-a105-47e1f88a896f.png)

Структура такая же, но название корневого тэга другое, и никак не могу найти как его поменять (если возможно). 
xmlRootAttribute меняет имя класса, но не массива.
Если создать класс, содержащий только этот массив (List) - название можно поменять, но появляется дополнительный уровень вложенности, что меняет структуру xml.

Подскажите пожалуйста, что можно с этим сделать.
Можно ли как-то этот тэг переименовать?
Или при десериализации читать разные варианты названий?
Влияют ли эти метаданные в 1-2 строках на сериализацию? Если да, подскажите, как их привести к единому виду.

**Comment by alexander-rykov** [comment]
_"Если создать класс, содержащий только этот массив (List) - название можно поменять, но появляется дополнительный уровень вложенности, что меняет структуру xml."_

именно так - создать новый класс, в котором будет лежать поле List или []. к полю нужно применить атрибут XmlElement. см. https://docs.microsoft.com/en-us/dotnet/standard/serialization/controlling-xml-serialization-using-attributes

**Comment by Gymbotan** [comment]
Можно попробовать реализовать 2 метода для чтения xml - один  для чтения xml, сформированного генератором, другой - для чтения xml послсе экспорта из нашей программы. Но мне кажется,что это решение не очень красивое и вы хотели научить нас чему-то другому, нежели создавать кучу методов для разных вариантов

**Comment by Gymbotan** [comment]
И правда совпало:
![изображение](https://user-images.githubusercontent.com/55342311/136187013-03b19302-2d60-4a5d-af5b-f58c7700ca2c.png)

Спасибо большое.
А подскажите еще, подчеркнутая часть будет влиять на десериализацию? Или это вспомогательные метаданные какие-то, просто для информации. А при (де)сериализации они игнорируются?

**Comment by alexander-rykov** [comment]
в случае этого задания эти вспомогательные атрибуты не нужны и будут игнорироваться.

**Comment by Gymbotan** [comment]
Прочитало. Еще раз большое спасибо, Александр
