### ISSUE TITLE
Шаг 10: Chain of Responsibility для комманд сервиса

### ISSUE THREAD

**Issue by MaksimPrudnikau** [epam-dotnet-lab/file-cabinet-task#85]
Здравствуйте. Исходя из прочитанной литературы по [Chain of Responsibility](https://refactoring.guru/ru/design-patterns/chain-of-responsibility), сделал вывод, что данный паттерн применяется в случае, когда обработка запроса производится последовательно. В нашем случае паттерн применяется для обработки комманд сервиса, полученных от пользователя. Комманды сервиса самостоятельны и их выполнение не зависит друг от друга. _Chain of Responsibility_ мне кажется более очевидным в применении для валидаторов, но по заданию он применяется не для них. 
В задании иллюстрация работы `Main` предложена только на первом шаге рефакторинга. К его концу, к сожалению, не могу представить работу функции. Как должна быть организована обработка комманд в `Main` при завершении данного шага?

**Comment by alexander-rykov** [comment]
"Цепочка обязанностей — это поведенческий паттерн проектирования, который позволяет ПЕРЕДАВАТЬ запросы ПОСЛЕДОВАТЕЛЬНО по цепочке обработчиков. Каждый последующий ОБРАБОТЧИК РЕШАЕТ, может ли он обработать запрос сам и стоит ли передавать запрос дальше по цепи."

в задании "запрос" - это объект AppCommandRequest, который передается последовательно по цепочке обработчиков, каждый из которых решает, обработать запрос или передать запрос дальше по цепи.

Польза от применения шаблона CoR:
* код каждого обработчика локализирован в одном классе.
* при добавлении нового обработчика, добавляется новый класс и изменяется код настройки обработчиков.
* при изменении функциональности обработчика, изменяется код одного класса.

"Как должна быть организована обработка комманд в Main при завершении данного шага?" - в этом и состоит задание, часть информации вы получаете, а часть - придумываете (додумываете) самостоятельно.
