### ISSUE TITLE
13:  команда update

### ISSUE THREAD

**Issue by anonimCitizen** [epam-dotnet-lab/file-cabinet-task#86]
Здравствуйте, может ли в условии where присутствовать оператор "or"?
Например, update set firstname = 'John', lastname = 'Doe' , dateofbirth = '5/18/1990' where id = '1' or lastname = 'Koe' and dateofbirth = '5/18/1990'

**Comment by alexander-rykov** [comment]
OR сложнее реализовывать чем AND, поэтому мы не требуем. если сможете - честь, хвала и почет.

**Comment by anonimCitizen** [comment]
спасибо
