### ISSUE TITLE
Шаг 12: в целом уточнить задание

### ISSUE THREAD

**Issue by Gymbotan** [epam-dotnet-lab/file-cabinet-task#87]
Предусловие: "Для FileCabinetMemoryService оставьте прежнее поведение", поэтому далее говорим только про FileCabinetFilesystemService.
1. При работе с файлом нам нужно создать 3 условных Dictionary<string, List "int"> для более быстрого поиска по параметрам. В листе хранится список смещений нужных записей. При этом, поскольку они хранятся в ОЗУ, то при каждом запуске они будут обнуляться. Поэтому при каждом запуске мы должны пройти весь файл и создать эти индексаторы. И обновлять их после CRUD операций. Так?
2. Далее написано "Методы сервиса Find... возвращают заранее коллекцию элементов, таким образом вычисление всех элементов коллекции должно происходить заранее". Но мы же храним только смещения, сами записи(record) мы же не храним, а будем, получается, считывать только после вызова методов Find... Где здесь вычисление заранее? Чего я не понимаю?
3. Чтобы осуществить считывание, мы перебираем значения из List и считываем записи  из этих мест. При этом в List'е есть свой итератор. К чему нужно прикручивать свой итератор? Какой перебор нам нужно реализовать самим?

**Comment by alexander-rykov** [comment]
1. "Поэтому при каждом запуске мы должны пройти весь файл и создать эти индексаторы. И обновлять их после CRUD операций. Так?" - верно
2. "Где здесь вычисление заранее? Чего я не понимаю?" - после того, как определены записи, которые нужно загрузить, их можно загрузить все целиком или загружать по одному на каждой итерации. под высчислением понимаются действия, которые приводят к формированию результирующего списка. итератор должен "вычислять" последовательность (то есть формировать результирующий список) в "ленивом" режиме, то есть загружать только одну запись на каждой итерации.
3. см. диаграмму - метод GetNext() должен загружать запись из файла на каждой итерации.
