### ISSUE TITLE
Шаг 2: no fast-forward слияние 

### ISSUE THREAD

**Issue by DaRy-Rise** [epam-dotnet-lab/file-cabinet-task#88]
Как в Visual studio сделать no fast-forward слияние? Я нашла по умолчанию просто слияние веток, без каких либо уточнений
![image](https://user-images.githubusercontent.com/64958256/140122845-91a7ffcc-e16e-4fdd-b76a-ecc606c2030e.png)

**Comment by DaRy-Rise** [comment]
Как в Visual studio сделать no fast-forward слияние? Я нашла по умолчанию просто слияние веток, без каких либо уточнений

**Comment by alexander-rykov** [comment]
делайте через консоль.
