### ISSUE TITLE
Шаг 8: При десериализации XML в методе ReadAll() выкидывает ошибку

### ISSUE THREAD

**Issue by SergeiSmazheluk** [epam-dotnet-lab/file-cabinet-task#89]
![image](https://user-images.githubusercontent.com/89450398/140282627-76b7060f-e197-41f3-8764-461d65ce77ab.png)

Здравствуйте,
В методе ReadAll() для десериализации в XmlSerializer передаю тип класса typeof(Record). Этот класс содержит список записей, которые содержат свойство Name и типа класса Name, который содержит поля FirstName и LastNamе. Эти классы специально создавал на шаге, где необходимо было сохранить в xml  файл сгенерированные записи, и чтобы они соответствовали схеме ...<name first="Petr" last="Semenov" />
Подскажите, пожалуйста, тот ли класс я передаю для XmlSerializer? в чем может быть ошибка, если класс норм?

**Comment by alexander-rykov** [comment]
посмотрите в filexml.xml, что там находится

**Comment by SergeiSmazheluk** [comment]
![image](https://user-images.githubusercontent.com/89450398/140333242-9752363c-cf38-4a71-8aad-3784d861647a.png)
Одна сохраненная запись

**Comment by SergeiSmazheluk** [comment]
Для тех, у кого будет похожая проблема: 
у меня в файле xml была запись cо string, а при десериализации я пытался получить char, когда поменял в промежуточном классе (который мы создавали для Name) для записи char на string, то все ок.
