### ISSUE TITLE
Шаг 8: XML cериализация

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/file-cabinet-task#9]
В задании "Генератор данны" в пункте 5 сказано "реализуйте экспорт данных в файл формата XML. Для создания XML-документа используйте XmlSerializer и атрибуты (XmlRoot, XmlElement, XmlAttribute)" в задании "Импорт XML" сказано "реализуйте новую команду "import xml" по аналогии с командой "import csv". Используйте десериализацию с помощью XmlSerializer и атрибутов." Из вышесказанного следует, что мы дожны сериализовать модель FileCabinetRecord, но сериализовать только с помощью атрибутов в структуру описанную в шаге 6 (https://github.com/epam-dotnet-lab/file-cabinet-task/blob/version1/step06.md) не получится, без создания дополнительной модели. Тогда получается, что после десериализации нам нужно создавать FileCabinetRecord и заполнять ее данными из "сериализуемой модели", которая по своей структуре отличается. Все это требует больших накладных расходов по создание промежуточных объектов. Можно подробнее разъяснить по данным пунктам?

Пример работы с атрибутами, как я понял, должен выглядеть похожим образом:
https://stackoverflow.com/questions/13811991/xml-serialization-of-a-list-with-attributes

**Comment by alexander-rykov** [comment]
@vitalmizevich:

_не получится, без создания дополнительной модели. Тогда получается, что после десериализации нам нужно создавать FileCabinetRecord и заполнять ее данными из "сериализуемой модели", которая по своей структуре отличается._

все верно - у вас есть сущность "бизнес области" FileCabinetRecord и модель для десериализации. считайте, что первое это - уровень BLL, а второе - уровень DAL. 

_Все это требует больших накладных расходов по создание промежуточных объектов. Можно подробнее разъяснить по данным пунктам?_

накладные расходов будут большими только в зависимости от количества объектов в файле импорта. попробуйте найти значение при котором сериализатор поперхнется.

_Пример работы с атрибутами, как я понял, должен выглядеть похожим образом:_

да, вот официальная документация
https://docs.microsoft.com/en-us/dotnet/standard/serialization/examples-of-xml-serialization
https://docs.microsoft.com/en-us/dotnet/standard/serialization/attributes-that-control-xml-serialization

**Comment by vitalmizevich** [comment]
> накладные расходов будут большими только в зависимости от количества объектов в файле импорта. попробуйте найти значение при котором сериализатор поперхнется.

Удалось успешно импортировать 10.000.000 записей. Исходный xml файл имел размер более 2 Гб.
Значение, при котором сериализатор должен "поперхнуть" не определил.

**Comment by alexander-rykov** [comment]
@vitalmizevich вы можете понаблюдать за поведением приложения во время импорта при помощи [Performance Monitor](http://tavalik.ru/performance-monitor-sborshhiki-dannyx/) (Системный монитор Windows).

Примеры
https://michaelscodingspot.com/performance-counters/
https://www.monitis.com/blog/improving-net-performance-part-17-measuring-net-application-performance-ii/

Вас должны интересовать [Memory Performance Counters](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/performance-counters#memory-performance-counters):
% Time in GC
_#_ Bytes in all Heaps
_#_ Gen 0 Collections
_#_ Gen 1 Collections
_#_ Gen 2 Collections
Gen 0 heap size
Gen 1 heap size
Gen 2 heap size

Сразу будет понятно, как себя ведет приложение в разрезе памяти.

**Comment by vitalmizevich** [comment]
Попробовал посмотреть в разрезе памяти, но особо понять ничего не вышло
![image](https://user-images.githubusercontent.com/20145590/67149849-064b9900-f2b9-11e9-8b69-83acb6415814.png)

**Comment by alexander-rykov** [comment]
@vitalmizevich 

1) Чтобы уменьшить количество мусора при добавлении счетчиков выбирайте только ваше приложение в Instances of selected object.

2) Вам потребуется 2 версии приложения - текущая и слегка измененная, которая загружает данные из XML непосредственно в FileCabinetRecord, минуя лишний объект. Для этого придется временно изменить генератор XML и структуру XML, чтобы получалась удобная для импорта структура. Тогда вы сможете сравнить поведение этих двух приложений по памяти.

**Comment by alexander-rykov** [comment]
@vitalmizevich извините. .NET Core приложения не поддерживают Performance Counters в Windows, нужны дополнительные телодвижения, чтобы посмотреть поведение приложения.

https://medium.com/criteo-labs/net-core-counters-internals-how-to-integrate-counters-in-your-monitoring-pipeline-5354cd61b42e

**Comment by alexander-rykov** [comment]
@vitalmizevich 

освоить новый инструментарий оказалось просто - https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/

$ dotnet tool install --global dotnet-counters
$ dotnet-counters list-processes
     13676 FileCabinetApp D:\Work\github\vitalmizevich\FileCabinet\FileCabinetApp\bin\Debug\netcoreapp3.0\FileCabinetApp.exe
$ dotnet-counters monitor --process-id 13676 System.Runtime

Для 1.000.000 записей показания такие:
![FileCabinetApp-dotnet-counters-1000000](https://user-images.githubusercontent.com/19323417/67151264-49fbce00-f2cc-11e9-8d06-3e32804b197f.png)

**Comment by vitalmizevich** [comment]
Что происходит с памятью относительно понятно (во время импорта объекты, по итогу, попадают во 2 поколение).

Так а что Вы имели ввиду под словом "поперхнуться"? Я изначально предполагал, что из-за большого размера должен появиться какой-то exception и поэтому пытался импортировать очень объемные документы. 
Но теперь, после развернутого ответа выше, Вы скорее намекали на количество записей, при котором количество объектов в старших поколениях будет выглядеть по-другому. Вы это имели ввиду?

> накладные расходов будут большими только в зависимости от количества объектов в файле импорта. попробуйте найти значение при котором сериализатор поперхнется.

**Comment by alexander-rykov** [comment]
@vitalmizevich я предполагаю, что сериализатор сломается, только столкнувшись с OOM, а до этого будет спокойно грызть XML не обращая внимания на количество объектов.

Во-вторых, мне любопытно, что gc сделает с объектами, которые участвуют в сериализации. Массив list попал в loh, сами filecabinetrecord - в gc 2 soh, а вот технические объекты для сериализации gc должен прибрать (если у него дойдут руки до gc collect 2).

Нужно сравнить с приложением без технических объектов, тогда будет видно насколько их использование затратно.
