### ISSUE TITLE
14: Приоритет операторов

### ISSUE THREAD

**Issue by anonimCitizen** [epam-dotnet-lab/file-cabinet-task#90]
Здравствуйте, операторы "or" и "and" имеют одинаковый приоритет?

**Comment by alexander-rykov** [comment]
а где в задании говорится про OR?

**Comment by anonimCitizen** [comment]
Критерии поиска могут быть составными с использованием операторов "and" или "or".

**Comment by alexander-rykov** [comment]
"поддержка совместной работы "and" и "or" не обязательна". обычно AND имеет более высокий приоритет чем OR.
