### ISSUE TITLE
Шаг 2: создание файлов с классами по пунктам 2-5

### ISSUE THREAD

**Issue by lavce1zar** [epam-dotnet-lab/file-cabinet-task#98]
По условию задания не понял допустимо ли создавать файлы FileCabinetRecord.cs и FileCabinetService.cs в VS. Но попробовал и в ней создать и без нее. В обоих случаях после создания первого класса при сборке в консоли выдает предупреждение CS8618 (а если создавать не в VS, то еще и SA1412). После создание второго файла в консоли выдаются те же самые предупреждения, а предупреждения, которые указаны в пункте 5 шага, отсутствуют. При этом в самой VS предупреждения присутствуют.

Вопрос: можно ли продолжать выполнение задания в случае если в консоли отсутствуют указанные в пункте 5 предупреждения, учитывая то, что они фигурируют в VS? и можно ли соответственно в дальнейшем при условии "создать файл .cs и добавить в него класс" выполнять это в самой VS?

**Comment by alexander-rykov** [comment]
"По условию задания не понял допустимо ли создавать файлы FileCabinetRecord.cs и FileCabinetService.cs в VS" - да.

"а если создавать не в VS, то еще и SA1412" - вполне возможно. нужно пересохранить файл с кодировкой UTF-8 with BOM.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1412.md

"В обоих случаях после создания первого класса при сборке в консоли выдает предупреждение CS8618" - [nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) это относительно новая фича языка С#. попробуйте добавить ? для reference type при описании переменной:

private static object? _field;

как вариант отключить nullable ref types в файле проекта (FileCabinet.csproj)

```csproj
<Nullable>enable</Nullable>
```
